<?php



function page_top(){
echo " <!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Strict//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd\">\n";
echo " <html xmlns=\"http://www.w3.org/1999/xhtml\" xml:lang=\"en\">\n";
echo " <head>\n";
echo " <title>Quake-Catcher Network</title>\n";
echo " <link rel=\"stylesheet\" type=\"text/css\" href=\"http://qcn.stanford.edu/css/base.css\" media=\"all\" />\n";
echo " <link rel=\"stylesheet\" type=\"text/css\" href=\"http://qcn.stanford.edu/css/top_rightsidebar.css\" media=\"screen\" />\n";
echo " <link rel=\"stylesheet\" type=\"text/css\" href=\"http://qcn.stanford.edu/css/print.css\" media=\"print\" />\n";
echo " <script type=\"text/javascript\" src=\"http://qcn.stanford.edu/=scripts/winpopup.js\"></script>\n";
echo " </head>\n";
echo " <body bgcolor=\"#999999\">\n";
echo " <div id=\"skipnav\"><a href=\"#maincontent\">Skip navigation</a></div>\n";


echo " <div id=\"container\">\n";
echo "   <div id=\"banner\"><img src=\"http://qcn.stanford.edu/images/banner.gif\" alt=\"Quake-Catcher Network\" title=\"Quake-Catcher Network\" width=\"100%\" /></div>\n";
echo "   <table width=\"100%\"><tr><td>\n";
echo "   <div id=\"nav\"> \n";
echo "     <ul>\n";
echo "       <li><a href=\"http://qcn.stanford.edu/index.php\">Home</a></li>\n";
echo "       <li><a href=\"http://qcn.stanford.edu/index.php?pg=about/index.html\">About QCN </a>\n";
echo " 	  <ul>\n";

echo "           <li><a href=\"http://qcn.stanford.edu/index.php?pg=about/laptop.html\">Laptop Network</a></li>\n";
echo "           <li><a href=\"http://qcn.stanford.edu/index.php?pg=about/desktop.html\">Desktop Network</a></li>\n";
echo "           <li><a href=\"http://qcn.stanford.edu/index.php?pg=about/contact.html\">Contact Us</a></li>\n";
echo "         </ul>\n";
echo "       <li><a href=\"http://qcn.stanford.edu/?pg=press/news.html\">News & Press</a>\n";
echo "         <ul>\n";

echo "           <li><a href=\"http://qcn.stanford.edu/?pg=press/news.html\">Recent News</a></li>\n";
echo "           <li><a href=\"http://qcn.stanford.edu/?pg=press/releases.html\">Press Releases</a></li>\n";
echo "           <li><a href=\"http://qcn.stanford.edu/images/\">Images</a></li>\n";
echo "           <li><a href=\"http://qcn.stanford.edu/?pg=press/videos.html\">Videos</a></li>\n";
echo "           <li><a href=\"http://qcn.stanford.edu/?pg=press/facts.html\">Facts</a></li>\n";
echo "         </ul>\n";
echo "       </li>\n";
echo "       <li><a href=\"http://qcn.stanford.edu/community/\">Community</a>\n";
echo " 	 <ul>\n";
echo "           <li><a href=\"http://qcn.stanford.edu/sensor/forum_index.php\">Message Boards</a></li>\n";
echo "           <li><a href=\"http://qcn.stanford.edu/sensor/user_search.php\">User Database</a></li>\n";
echo "           <li><a href=\"http://qcn.stanford.edu/sensor/stats.php\">Statistics</a></li>\n";
echo "          </ul>\n";
        
echo "       <li><a href=\"http://qcn.stanford.edu/index.php?pg=learning/index.html\">Learning Center </a>\n";
echo " 	  <ul>\n";
echo "           <li><a href=\"http://qcn.stanford.edu/index.php?pg=learning/software.html\">QCNLive</a></li>\n";
echo "           <li><a href=\"http://qcn.stanford.edu/index.php?pg=learning/lessons.html\">Lessons & Activities</a></li>\n";
echo "           <li><a href=\"http://qcn.stanford.edu/index.php?pg=downloads/index.html\">Software Download</a>\n";
echo "           <li><a href=\"http://qcn.stanford.edu/index.php?pg=learning/earthquakes.html\">Learn About Earthquakes</a></li>\n";
echo " 	  <li><a href=\"http://qcn.stanford.edu/index.php?pg=learning/requests.html\">Sensor Requests</a></li>\n";
echo "           <li><a href=\"http://qcn.stanford.edu/index.php?pg=learning/glossary.html\">Glossary</a></li>\n";
echo "         </ul>\n";
echo "       <li><a href=\"http://qcn.stanford.edu/index.php?pg=research/index.html\">Research Center</a>\n";
echo "  	  <ul>\n";

echo "           <li><a href=\"http://qcn.stanford.edu/index.php?pg=research/data.html\">Data Download</a></li>\n";
echo "           <li><a href=\"http://qcn.stanford.edu/index.php?pg=research/opportunities.index.html\">Development Opportunities</a></li>\n";
echo "           <li><a href=\"http://qcn.stanford.edu/index.php?pg=downloads/index.html\">Software Download</a>\n";

echo "         </ul>\n";
echo "       <li><a href=\"http://qcn.stanford.edu/sensor/\">My QCN/BOINC</a>\n";
echo "  	  <ul>\n";

echo "           <li><a href=\"http://qcn.stanford.edu/sensor/home.php\">My Account</a></li>\n";
echo "           <li><a href=\"http://qcn.stanford.edu/sensor/edit_host_info_form.php\">My Location</a></li>\n";
echo "            <li><a href=\"http://qcn.stanford.edu/index.php?pg=downloads/index.html\">Software Download</a>\n";
echo "         </ul>\n";
    



echo " <li><a href=\"\">Translate\n</a>";
echo " <ul>\n";
echo "   <li><a href=\"javascript:var t=((window.getSelection&amp;&amp;window.getSelection())||(document.getSelection&amp;&amp;document.getSelection())||(document.selection&amp;&amp;document.selection.createRange&amp;&amp;document.selection.createRange().text));var e=(document.charset||document.characterSet);if(t!=''){location.href='http://translate.google.com/translate_t?text='+t+'&amp;hl=en&amp;langpair=auto|af&amp;tbb=1&amp;ie='+e;}else{location.href='http://translate.google.com/translate?u='+escape(location.href)+'&amp;hl=en&amp;langpair=auto|af&amp;tbb=1&amp;ie='+e;};\" onclick=\"alert(document.getElementById('instructions').firstChild.nodeValue);return false;\">Afrikaans</a></li>\n";
echo "   <li><a href=\"javascript:var t=((window.getSelection&amp;&amp;window.getSelection())||(document.getSelection&amp;&amp;document.getSelection())||(document.selection&amp;&amp;document.selection.createRange&amp;&amp;document.selection.createRange().text));var e=(document.charset||document.characterSet);if(t!=''){location.href='http://translate.google.com/translate_t?text='+t+'&amp;hl=en&amp;langpair=auto|sq&amp;tbb=1&amp;ie='+e;}else{location.href='http://translate.google.com/translate?u='+escape(location.href)+'&amp;hl=en&amp;langpair=auto|sq&amp;tbb=1&amp;ie='+e;};\" onclick=\"alert(document.getElementById('instructions').firstChild.nodeValue);return false;\">Albanian</a></li>\n";
echo "   <li><a href=\"javascript:var t=((window.getSelection&amp;&amp;window.getSelection())||(document.getSelection&amp;&amp;document.getSelection())||(document.selection&amp;&amp;document.selection.createRange&amp;&amp;document.selection.createRange().text));var e=(document.charset||document.characterSet);if(t!=''){location.href='http://translate.google.com/translate_t?text='+t+'&amp;hl=en&amp;langpair=auto|ar&amp;tbb=1&amp;ie='+e;}else{location.href='http://translate.google.com/translate?u='+escape(location.href)+'&amp;hl=en&amp;langpair=auto|ar&amp;tbb=1&amp;ie='+e;};\" onclick=\"alert(document.getElementById('instructions').firstChild.nodeValue);return false;\">Arabic</a></li>\n";
echo "   <li><a href=\"javascript:var t=((window.getSelection&amp;&amp;window.getSelection())||(document.getSelection&amp;&amp;document.getSelection())||(document.selection&amp;&amp;document.selection.createRange&amp;&amp;document.selection.createRange().text));var e=(document.charset||document.characterSet);if(t!=''){location.href='http://translate.google.com/translate_t?text='+t+'&amp;hl=en&amp;langpair=auto|be&amp;tbb=1&amp;ie='+e;}else{location.href='http://translate.google.com/translate?u='+escape(location.href)+'&amp;hl=en&amp;langpair=auto|be&amp;tbb=1&amp;ie='+e;};\" onclick=\"alert(document.getElementById('instructions').firstChild.nodeValue);return false;\">Belarusian</a></li>\n";
echo "   <li><a href=\"javascript:var t=((window.getSelection&amp;&amp;window.getSelection())||(document.getSelection&amp;&amp;document.getSelection())||(document.selection&amp;&amp;document.selection.createRange&amp;&amp;document.selection.createRange().text));var e=(document.charset||document.characterSet);if(t!=''){location.href='http://translate.google.com/translate_t?text='+t+'&amp;hl=en&amp;langpair=auto|bg&amp;tbb=1&amp;ie='+e;}else{location.href='http://translate.google.com/translate?u='+escape(location.href)+'&amp;hl=en&amp;langpair=auto|bg&amp;tbb=1&amp;ie='+e;};\" onclick=\"alert(document.getElementById('instructions').firstChild.nodeValue);return false;\">Bulgarian</a></li>\n";
echo "   <li><a href=\"javascript:var t=((window.getSelection&amp;&amp;window.getSelection())||(document.getSelection&amp;&amp;document.getSelection())||(document.selection&amp;&amp;document.selection.createRange&amp;&amp;document.selection.createRange().text));var e=(document.charset||document.characterSet);if(t!=''){location.href='http://translate.google.com/translate_t?text='+t+'&amp;hl=en&amp;langpair=auto|ca&amp;tbb=1&amp;ie='+e;}else{location.href='http://translate.google.com/translate?u='+escape(location.href)+'&amp;hl=en&amp;langpair=auto|ca&amp;tbb=1&amp;ie='+e;};\" onclick=\"alert(document.getElementById('instructions').firstChild.nodeValue);return false;\">Catalan</a></li>\n";
echo "   <li><a href=\"javascript:var t=((window.getSelection&amp;&amp;window.getSelection())||(document.getSelection&amp;&amp;document.getSelection())||(document.selection&amp;&amp;document.selection.createRange&amp;&amp;document.selection.createRange().text));var e=(document.charset||document.characterSet);if(t!=''){location.href='http://translate.google.com/translate_t?text='+t+'&amp;hl=en&amp;langpair=auto|zh-CN&amp;tbb=1&amp;ie='+e;}else{location.href='http://translate.google.com/translate?u='+escape(location.href)+'&amp;hl=en&amp;langpair=auto|zh-CN&amp;tbb=1&amp;ie='+e;};\" onclick=\"alert(document.getElementById('instructions').firstChild.nodeValue);return false;\">Chinese (Simplified)</a></li>\n";
echo "   <li><a href=\"javascript:var t=((window.getSelection&amp;&amp;window.getSelection())||(document.getSelection&amp;&amp;document.getSelection())||(document.selection&amp;&amp;document.selection.createRange&amp;&amp;document.selection.createRange().text));var e=(document.charset||document.characterSet);if(t!=''){location.href='http://translate.google.com/translate_t?text='+t+'&amp;hl=en&amp;langpair=auto|zh-TW&amp;tbb=1&amp;ie='+e;}else{location.href='http://translate.google.com/translate?u='+escape(location.href)+'&amp;hl=en&amp;langpair=auto|zh-TW&amp;tbb=1&amp;ie='+e;};\" onclick=\"alert(document.getElementById('instructions').firstChild.nodeValue);return false;\">Chinese (Traditional)</a></li>\n";
echo "   <li><a href=\"javascript:var t=((window.getSelection&amp;&amp;window.getSelection())||(document.getSelection&amp;&amp;document.getSelection())||(document.selection&amp;&amp;document.selection.createRange&amp;&amp;document.selection.createRange().text));var e=(document.charset||document.characterSet);if(t!=''){location.href='http://translate.google.com/translate_t?text='+t+'&amp;hl=en&amp;langpair=auto|hr&amp;tbb=1&amp;ie='+e;}else{location.href='http://translate.google.com/translate?u='+escape(location.href)+'&amp;hl=en&amp;langpair=auto|hr&amp;tbb=1&amp;ie='+e;};\" onclick=\"alert(document.getElementById('instructions').firstChild.nodeValue);return false;\">Croatian</a></li>\n";
echo "   <li><a href=\"javascript:var t=((window.getSelection&amp;&amp;window.getSelection())||(document.getSelection&amp;&amp;document.getSelection())||(document.selection&amp;&amp;document.selection.createRange&amp;&amp;document.selection.createRange().text));var e=(document.charset||document.characterSet);if(t!=''){location.href='http://translate.google.com/translate_t?text='+t+'&amp;hl=en&amp;langpair=auto|cs&amp;tbb=1&amp;ie='+e;}else{location.href='http://translate.google.com/translate?u='+escape(location.href)+'&amp;hl=en&amp;langpair=auto|cs&amp;tbb=1&amp;ie='+e;};\" onclick=\"alert(document.getElementById('instructions').firstChild.nodeValue);return false;\">Czech</a></li>\n";
echo "   <li><a href=\"javascript:var t=((window.getSelection&amp;&amp;window.getSelection())||(document.getSelection&amp;&amp;document.getSelection())||(document.selection&amp;&amp;document.selection.createRange&amp;&amp;document.selection.createRange().text));var e=(document.charset||document.characterSet);if(t!=''){location.href='http://translate.google.com/translate_t?text='+t+'&amp;hl=en&amp;langpair=auto|da&amp;tbb=1&amp;ie='+e;}else{location.href='http://translate.google.com/translate?u='+escape(location.href)+'&amp;hl=en&amp;langpair=auto|da&amp;tbb=1&amp;ie='+e;};\" onclick=\"alert(document.getElementById('instructions').firstChild.nodeValue);return false;\">Danish</a></li>\n";
echo "   <li><a href=\"javascript:var t=((window.getSelection&amp;&amp;window.getSelection())||(document.getSelection&amp;&amp;document.getSelection())||(document.selection&amp;&amp;document.selection.createRange&amp;&amp;document.selection.createRange().text));var e=(document.charset||document.characterSet);if(t!=''){location.href='http://translate.google.com/translate_t?text='+t+'&amp;hl=en&amp;langpair=auto|nl&amp;tbb=1&amp;ie='+e;}else{location.href='http://translate.google.com/translate?u='+escape(location.href)+'&amp;hl=en&amp;langpair=auto|nl&amp;tbb=1&amp;ie='+e;};\" onclick=\"alert(document.getElementById('instructions').firstChild.nodeValue);return false;\">Dutch</a></li>\n";
echo "   <li><a href=\"javascript:var t=((window.getSelection&amp;&amp;window.getSelection())||(document.getSelection&amp;&amp;document.getSelection())||(document.selection&amp;&amp;document.selection.createRange&amp;&amp;document.selection.createRange().text));var e=(document.charset||document.characterSet);if(t!=''){location.href='http://translate.google.com/translate_t?text='+t+'&amp;hl=en&amp;langpair=auto|en&amp;tbb=1&amp;ie='+e;}else{location.href='http://translate.google.com/translate?u='+escape(location.href)+'&amp;hl=en&amp;langpair=auto|en&amp;tbb=1&amp;ie='+e;};\" onclick=\"alert(document.getElementById('instructions').firstChild.nodeValue);return false;\">English</a></li>\n";
echo "   <li><a href=\"javascript:var t=((window.getSelection&amp;&amp;window.getSelection())||(document.getSelection&amp;&amp;document.getSelection())||(document.selection&amp;&amp;document.selection.createRange&amp;&amp;document.selection.createRange().text));var e=(document.charset||document.characterSet);if(t!=''){location.href='http://translate.google.com/translate_t?text='+t+'&amp;hl=en&amp;langpair=auto|et&amp;tbb=1&amp;ie='+e;}else{location.href='http://translate.google.com/translate?u='+escape(location.href)+'&amp;hl=en&amp;langpair=auto|et&amp;tbb=1&amp;ie='+e;};\" onclick=\"alert(document.getElementById('instructions').firstChild.nodeValue);return false;\">Estonian</a></li>\n";
echo "   <li><a href=\"javascript:var t=((window.getSelection&amp;&amp;window.getSelection())||(document.getSelection&amp;&amp;document.getSelection())||(document.selection&amp;&amp;document.selection.createRange&amp;&amp;document.selection.createRange().text));var e=(document.charset||document.characterSet);if(t!=''){location.href='http://translate.google.com/translate_t?text='+t+'&amp;hl=en&amp;langpair=auto|tl&amp;tbb=1&amp;ie='+e;}else{location.href='http://translate.google.com/translate?u='+escape(location.href)+'&amp;hl=en&amp;langpair=auto|tl&amp;tbb=1&amp;ie='+e;};\" onclick=\"alert(document.getElementById('instructions').firstChild.nodeValue);return false;\">Filipino</a></li>\n";
echo "   <li><a href=\"javascript:var t=((window.getSelection&amp;&amp;window.getSelection())||(document.getSelection&amp;&amp;document.getSelection())||(document.selection&amp;&amp;document.selection.createRange&amp;&amp;document.selection.createRange().text));var e=(document.charset||document.characterSet);if(t!=''){location.href='http://translate.google.com/translate_t?text='+t+'&amp;hl=en&amp;langpair=auto|fi&amp;tbb=1&amp;ie='+e;}else{location.href='http://translate.google.com/translate?u='+escape(location.href)+'&amp;hl=en&amp;langpair=auto|fi&amp;tbb=1&amp;ie='+e;};\" onclick=\"alert(document.getElementById('instructions').firstChild.nodeValue);return false;\">Finnish</a></li>\n";
echo "   <li><a href=\"javascript:var t=((window.getSelection&amp;&amp;window.getSelection())||(document.getSelection&amp;&amp;document.getSelection())||(document.selection&amp;&amp;document.selection.createRange&amp;&amp;document.selection.createRange().text));var e=(document.charset||document.characterSet);if(t!=''){location.href='http://translate.google.com/translate_t?text='+t+'&amp;hl=en&amp;langpair=auto|fr&amp;tbb=1&amp;ie='+e;}else{location.href='http://translate.google.com/translate?u='+escape(location.href)+'&amp;hl=en&amp;langpair=auto|fr&amp;tbb=1&amp;ie='+e;};\" onclick=\"alert(document.getElementById('instructions').firstChild.nodeValue);return false;\">French</a></li>\n";
echo "   <li><a href=\"javascript:var t=((window.getSelection&amp;&amp;window.getSelection())||(document.getSelection&amp;&amp;document.getSelection())||(document.selection&amp;&amp;document.selection.createRange&amp;&amp;document.selection.createRange().text));var e=(document.charset||document.characterSet);if(t!=''){location.href='http://translate.google.com/translate_t?text='+t+'&amp;hl=en&amp;langpair=auto|gl&amp;tbb=1&amp;ie='+e;}else{location.href='http://translate.google.com/translate?u='+escape(location.href)+'&amp;hl=en&amp;langpair=auto|gl&amp;tbb=1&amp;ie='+e;};\" onclick=\"alert(document.getElementById('instructions').firstChild.nodeValue);return false;\">Galician</a></li>\n";
echo "   <li><a href=\"javascript:var t=((window.getSelection&amp;&amp;window.getSelection())||(document.getSelection&amp;&amp;document.getSelection())||(document.selection&amp;&amp;document.selection.createRange&amp;&amp;document.selection.createRange().text));var e=(document.charset||document.characterSet);if(t!=''){location.href='http://translate.google.com/translate_t?text='+t+'&amp;hl=en&amp;langpair=auto|de&amp;tbb=1&amp;ie='+e;}else{location.href='http://translate.google.com/translate?u='+escape(location.href)+'&amp;hl=en&amp;langpair=auto|de&amp;tbb=1&amp;ie='+e;};\" onclick=\"alert(document.getElementById('instructions').firstChild.nodeValue);return false;\">German</a></li>\n";
echo "   <li><a href=\"javascript:var t=((window.getSelection&amp;&amp;window.getSelection())||(document.getSelection&amp;&amp;document.getSelection())||(document.selection&amp;&amp;document.selection.createRange&amp;&amp;document.selection.createRange().text));var e=(document.charset||document.characterSet);if(t!=''){location.href='http://translate.google.com/translate_t?text='+t+'&amp;hl=en&amp;langpair=auto|el&amp;tbb=1&amp;ie='+e;}else{location.href='http://translate.google.com/translate?u='+escape(location.href)+'&amp;hl=en&amp;langpair=auto|el&amp;tbb=1&amp;ie='+e;};\" onclick=\"alert(document.getElementById('instructions').firstChild.nodeValue);return false;\">Greek</a></li>\n";
echo "   <li><a href=\"javascript:var t=((window.getSelection&amp;&amp;window.getSelection())||(document.getSelection&amp;&amp;document.getSelection())||(document.selection&amp;&amp;document.selection.createRange&amp;&amp;document.selection.createRange().text));var e=(document.charset||document.characterSet);if(t!=''){location.href='http://translate.google.com/translate_t?text='+t+'&amp;hl=en&amp;langpair=auto|iw&amp;tbb=1&amp;ie='+e;}else{location.href='http://translate.google.com/translate?u='+escape(location.href)+'&amp;hl=en&amp;langpair=auto|iw&amp;tbb=1&amp;ie='+e;};\" onclick=\"alert(document.getElementById('instructions').firstChild.nodeValue);return false;\">Hebrew</a></li>\n";
echo "   <li><a href=\"javascript:var t=((window.getSelection&amp;&amp;window.getSelection())||(document.getSelection&amp;&amp;document.getSelection())||(document.selection&amp;&amp;document.selection.createRange&amp;&amp;document.selection.createRange().text));var e=(document.charset||document.characterSet);if(t!=''){location.href='http://translate.google.com/translate_t?text='+t+'&amp;hl=en&amp;langpair=auto|hi&amp;tbb=1&amp;ie='+e;}else{location.href='http://translate.google.com/translate?u='+escape(location.href)+'&amp;hl=en&amp;langpair=auto|hi&amp;tbb=1&amp;ie='+e;};\" onclick=\"alert(document.getElementById('instructions').firstChild.nodeValue);return false;\">Hindi</a></li>\n";
echo "   <li><a href=\"javascript:var t=((window.getSelection&amp;&amp;window.getSelection())||(document.getSelection&amp;&amp;document.getSelection())||(document.selection&amp;&amp;document.selection.createRange&amp;&amp;document.selection.createRange().text));var e=(document.charset||document.characterSet);if(t!=''){location.href='http://translate.google.com/translate_t?text='+t+'&amp;hl=en&amp;langpair=auto|hu&amp;tbb=1&amp;ie='+e;}else{location.href='http://translate.google.com/translate?u='+escape(location.href)+'&amp;hl=en&amp;langpair=auto|hu&amp;tbb=1&amp;ie='+e;};\" onclick=\"alert(document.getElementById('instructions').firstChild.nodeValue);return false;\">Hungarian</a></li>\n";
echo "   <li><a href=\"javascript:var t=((window.getSelection&amp;&amp;window.getSelection())||(document.getSelection&amp;&amp;document.getSelection())||(document.selection&amp;&amp;document.selection.createRange&amp;&amp;document.selection.createRange().text));var e=(document.charset||document.characterSet);if(t!=''){location.href='http://translate.google.com/translate_t?text='+t+'&amp;hl=en&amp;langpair=auto|is&amp;tbb=1&amp;ie='+e;}else{location.href='http://translate.google.com/translate?u='+escape(location.href)+'&amp;hl=en&amp;langpair=auto|is&amp;tbb=1&amp;ie='+e;};\" onclick=\"alert(document.getElementById('instructions').firstChild.nodeValue);return false;\">Icelandic</a></li>\n";
echo "   <li><a href=\"javascript:var t=((window.getSelection&amp;&amp;window.getSelection())||(document.getSelection&amp;&amp;document.getSelection())||(document.selection&amp;&amp;document.selection.createRange&amp;&amp;document.selection.createRange().text));var e=(document.charset||document.characterSet);if(t!=''){location.href='http://translate.google.com/translate_t?text='+t+'&amp;hl=en&amp;langpair=auto|id&amp;tbb=1&amp;ie='+e;}else{location.href='http://translate.google.com/translate?u='+escape(location.href)+'&amp;hl=en&amp;langpair=auto|id&amp;tbb=1&amp;ie='+e;};\" onclick=\"alert(document.getElementById('instructions').firstChild.nodeValue);return false;\">Indonesian</a></li>\n";
echo "   <li><a href=\"javascript:var t=((window.getSelection&amp;&amp;window.getSelection())||(document.getSelection&amp;&amp;document.getSelection())||(document.selection&amp;&amp;document.selection.createRange&amp;&amp;document.selection.createRange().text));var e=(document.charset||document.characterSet);if(t!=''){location.href='http://translate.google.com/translate_t?text='+t+'&amp;hl=en&amp;langpair=auto|ga&amp;tbb=1&amp;ie='+e;}else{location.href='http://translate.google.com/translate?u='+escape(location.href)+'&amp;hl=en&amp;langpair=auto|ga&amp;tbb=1&amp;ie='+e;};\" onclick=\"alert(document.getElementById('instructions').firstChild.nodeValue);return false;\">Irish</a></li>\n";
echo "   <li><a href=\"javascript:var t=((window.getSelection&amp;&amp;window.getSelection())||(document.getSelection&amp;&amp;document.getSelection())||(document.selection&amp;&amp;document.selection.createRange&amp;&amp;document.selection.createRange().text));var e=(document.charset||document.characterSet);if(t!=''){location.href='http://translate.google.com/translate_t?text='+t+'&amp;hl=en&amp;langpair=auto|it&amp;tbb=1&amp;ie='+e;}else{location.href='http://translate.google.com/translate?u='+escape(location.href)+'&amp;hl=en&amp;langpair=auto|it&amp;tbb=1&amp;ie='+e;};\" onclick=\"alert(document.getElementById('instructions').firstChild.nodeValue);return false;\">Italian</a></li>\n";
echo "   <li><a href=\"javascript:var t=((window.getSelection&amp;&amp;window.getSelection())||(document.getSelection&amp;&amp;document.getSelection())||(document.selection&amp;&amp;document.selection.createRange&amp;&amp;document.selection.createRange().text));var e=(document.charset||document.characterSet);if(t!=''){location.href='http://translate.google.com/translate_t?text='+t+'&amp;hl=en&amp;langpair=auto|ja&amp;tbb=1&amp;ie='+e;}else{location.href='http://translate.google.com/translate?u='+escape(location.href)+'&amp;hl=en&amp;langpair=auto|ja&amp;tbb=1&amp;ie='+e;};\" onclick=\"alert(document.getElementById('instructions').firstChild.nodeValue);return false;\">Japanese</a></li>\n";
echo "   <li><a href=\"javascript:var t=((window.getSelection&amp;&amp;window.getSelection())||(document.getSelection&amp;&amp;document.getSelection())||(document.selection&amp;&amp;document.selection.createRange&amp;&amp;document.selection.createRange().text));var e=(document.charset||document.characterSet);if(t!=''){location.href='http://translate.google.com/translate_t?text='+t+'&amp;hl=en&amp;langpair=auto|ko&amp;tbb=1&amp;ie='+e;}else{location.href='http://translate.google.com/translate?u='+escape(location.href)+'&amp;hl=en&amp;langpair=auto|ko&amp;tbb=1&amp;ie='+e;};\" onclick=\"alert(document.getElementById('instructions').firstChild.nodeValue);return false;\">Korean</a></li>\n";
echo "   <li><a href=\"javascript:var t=((window.getSelection&amp;&amp;window.getSelection())||(document.getSelection&amp;&amp;document.getSelection())||(document.selection&amp;&amp;document.selection.createRange&amp;&amp;document.selection.createRange().text));var e=(document.charset||document.characterSet);if(t!=''){location.href='http://translate.google.com/translate_t?text='+t+'&amp;hl=en&amp;langpair=auto|lv&amp;tbb=1&amp;ie='+e;}else{location.href='http://translate.google.com/translate?u='+escape(location.href)+'&amp;hl=en&amp;langpair=auto|lv&amp;tbb=1&amp;ie='+e;};\" onclick=\"alert(document.getElementById('instructions').firstChild.nodeValue);return false;\">Latvian</a></li>\n";
echo "   <li><a href=\"javascript:var t=((window.getSelection&amp;&amp;window.getSelection())||(document.getSelection&amp;&amp;document.getSelection())||(document.selection&amp;&amp;document.selection.createRange&amp;&amp;document.selection.createRange().text));var e=(document.charset||document.characterSet);if(t!=''){location.href='http://translate.google.com/translate_t?text='+t+'&amp;hl=en&amp;langpair=auto|lt&amp;tbb=1&amp;ie='+e;}else{location.href='http://translate.google.com/translate?u='+escape(location.href)+'&amp;hl=en&amp;langpair=auto|lt&amp;tbb=1&amp;ie='+e;};\" onclick=\"alert(document.getElementById('instructions').firstChild.nodeValue);return false;\">Lithuanian</a></li>\n";
echo "   <li><a href=\"javascript:var t=((window.getSelection&amp;&amp;window.getSelection())||(document.getSelection&amp;&amp;document.getSelection())||(document.selection&amp;&amp;document.selection.createRange&amp;&amp;document.selection.createRange().text));var e=(document.charset||document.characterSet);if(t!=''){location.href='http://translate.google.com/translate_t?text='+t+'&amp;hl=en&amp;langpair=auto|mk&amp;tbb=1&amp;ie='+e;}else{location.href='http://translate.google.com/translate?u='+escape(location.href)+'&amp;hl=en&amp;langpair=auto|mk&amp;tbb=1&amp;ie='+e;};\" onclick=\"alert(document.getElementById('instructions').firstChild.nodeValue);return false;\">Macedonian</a></li>\n";
echo "   <li><a href=\"javascript:var t=((window.getSelection&amp;&amp;window.getSelection())||(document.getSelection&amp;&amp;document.getSelection())||(document.selection&amp;&amp;document.selection.createRange&amp;&amp;document.selection.createRange().text));var e=(document.charset||document.characterSet);if(t!=''){location.href='http://translate.google.com/translate_t?text='+t+'&amp;hl=en&amp;langpair=auto|ms&amp;tbb=1&amp;ie='+e;}else{location.href='http://translate.google.com/translate?u='+escape(location.href)+'&amp;hl=en&amp;langpair=auto|ms&amp;tbb=1&amp;ie='+e;};\" onclick=\"alert(document.getElementById('instructions').firstChild.nodeValue);return false;\">Malay</a></li>\n";
echo "   <li><a href=\"javascript:var t=((window.getSelection&amp;&amp;window.getSelection())||(document.getSelection&amp;&amp;document.getSelection())||(document.selection&amp;&amp;document.selection.createRange&amp;&amp;document.selection.createRange().text));var e=(document.charset||document.characterSet);if(t!=''){location.href='http://translate.google.com/translate_t?text='+t+'&amp;hl=en&amp;langpair=auto|mt&amp;tbb=1&amp;ie='+e;}else{location.href='http://translate.google.com/translate?u='+escape(location.href)+'&amp;hl=en&amp;langpair=auto|mt&amp;tbb=1&amp;ie='+e;};\" onclick=\"alert(document.getElementById('instructions').firstChild.nodeValue);return false;\">Maltese</a></li>\n";
echo "   <li><a href=\"javascript:var t=((window.getSelection&amp;&amp;window.getSelection())||(document.getSelection&amp;&amp;document.getSelection())||(document.selection&amp;&amp;document.selection.createRange&amp;&amp;document.selection.createRange().text));var e=(document.charset||document.characterSet);if(t!=''){location.href='http://translate.google.com/translate_t?text='+t+'&amp;hl=en&amp;langpair=auto|no&amp;tbb=1&amp;ie='+e;}else{location.href='http://translate.google.com/translate?u='+escape(location.href)+'&amp;hl=en&amp;langpair=auto|no&amp;tbb=1&amp;ie='+e;};\" onclick=\"alert(document.getElementById('instructions').firstChild.nodeValue);return false;\">Norwegian</a></li>\n";
echo "   <li><a href=\"javascript:var t=((window.getSelection&amp;&amp;window.getSelection())||(document.getSelection&amp;&amp;document.getSelection())||(document.selection&amp;&amp;document.selection.createRange&amp;&amp;document.selection.createRange().text));var e=(document.charset||document.characterSet);if(t!=''){location.href='http://translate.google.com/translate_t?text='+t+'&amp;hl=en&amp;langpair=auto|fa&amp;tbb=1&amp;ie='+e;}else{location.href='http://translate.google.com/translate?u='+escape(location.href)+'&amp;hl=en&amp;langpair=auto|fa&amp;tbb=1&amp;ie='+e;};\" onclick=\"alert(document.getElementById('instructions').firstChild.nodeValue);return false;\">Persian</a></li>\n";
echo "   <li><a href=\"javascript:var t=((window.getSelection&amp;&amp;window.getSelection())||(document.getSelection&amp;&amp;document.getSelection())||(document.selection&amp;&amp;document.selection.createRange&amp;&amp;document.selection.createRange().text));var e=(document.charset||document.characterSet);if(t!=''){location.href='http://translate.google.com/translate_t?text='+t+'&amp;hl=en&amp;langpair=auto|pl&amp;tbb=1&amp;ie='+e;}else{location.href='http://translate.google.com/translate?u='+escape(location.href)+'&amp;hl=en&amp;langpair=auto|pl&amp;tbb=1&amp;ie='+e;};\" onclick=\"alert(document.getElementById('instructions').firstChild.nodeValue);return false;\">Polish</a></li>\n";
echo "   <li><a href=\"javascript:var t=((window.getSelection&amp;&amp;window.getSelection())||(document.getSelection&amp;&amp;document.getSelection())||(document.selection&amp;&amp;document.selection.createRange&amp;&amp;document.selection.createRange().text));var e=(document.charset||document.characterSet);if(t!=''){location.href='http://translate.google.com/translate_t?text='+t+'&amp;hl=en&amp;langpair=auto|pt&amp;tbb=1&amp;ie='+e;}else{location.href='http://translate.google.com/translate?u='+escape(location.href)+'&amp;hl=en&amp;langpair=auto|pt&amp;tbb=1&amp;ie='+e;};\" onclick=\"alert(document.getElementById('instructions').firstChild.nodeValue);return false;\">Portuguese</a></li>\n";
echo "   <li><a href=\"javascript:var t=((window.getSelection&amp;&amp;window.getSelection())||(document.getSelection&amp;&amp;document.getSelection())||(document.selection&amp;&amp;document.selection.createRange&amp;&amp;document.selection.createRange().text));var e=(document.charset||document.characterSet);if(t!=''){location.href='http://translate.google.com/translate_t?text='+t+'&amp;hl=en&amp;langpair=auto|ro&amp;tbb=1&amp;ie='+e;}else{location.href='http://translate.google.com/translate?u='+escape(location.href)+'&amp;hl=en&amp;langpair=auto|ro&amp;tbb=1&amp;ie='+e;};\" onclick=\"alert(document.getElementById('instructions').firstChild.nodeValue);return false;\">Romanian</a></li>\n";
echo "   <li><a href=\"javascript:var t=((window.getSelection&amp;&amp;window.getSelection())||(document.getSelection&amp;&amp;document.getSelection())||(document.selection&amp;&amp;document.selection.createRange&amp;&amp;document.selection.createRange().text));var e=(document.charset||document.characterSet);if(t!=''){location.href='http://translate.google.com/translate_t?text='+t+'&amp;hl=en&amp;langpair=auto|ru&amp;tbb=1&amp;ie='+e;}else{location.href='http://translate.google.com/translate?u='+escape(location.href)+'&amp;hl=en&amp;langpair=auto|ru&amp;tbb=1&amp;ie='+e;};\" onclick=\"alert(document.getElementById('instructions').firstChild.nodeValue);return false;\">Russian</a></li>\n";
echo "   <li><a href=\"javascript:var t=((window.getSelection&amp;&amp;window.getSelection())||(document.getSelection&amp;&amp;document.getSelection())||(document.selection&amp;&amp;document.selection.createRange&amp;&amp;document.selection.createRange().text));var e=(document.charset||document.characterSet);if(t!=''){location.href='http://translate.google.com/translate_t?text='+t+'&amp;hl=en&amp;langpair=auto|sr&amp;tbb=1&amp;ie='+e;}else{location.href='http://translate.google.com/translate?u='+escape(location.href)+'&amp;hl=en&amp;langpair=auto|sr&amp;tbb=1&amp;ie='+e;};\" onclick=\"alert(document.getElementById('instructions').firstChild.nodeValue);return false;\">Serbian</a></li>\n";
echo "   <li><a href=\"javascript:var t=((window.getSelection&amp;&amp;window.getSelection())||(document.getSelection&amp;&amp;document.getSelection())||(document.selection&amp;&amp;document.selection.createRange&amp;&amp;document.selection.createRange().text));var e=(document.charset||document.characterSet);if(t!=''){location.href='http://translate.google.com/translate_t?text='+t+'&amp;hl=en&amp;langpair=auto|sk&amp;tbb=1&amp;ie='+e;}else{location.href='http://translate.google.com/translate?u='+escape(location.href)+'&amp;hl=en&amp;langpair=auto|sk&amp;tbb=1&amp;ie='+e;};\" onclick=\"alert(document.getElementById('instructions').firstChild.nodeValue);return false;\">Slovak</a></li>\n";
echo "   <li><a href=\"javascript:var t=((window.getSelection&amp;&amp;window.getSelection())||(document.getSelection&amp;&amp;document.getSelection())||(document.selection&amp;&amp;document.selection.createRange&amp;&amp;document.selection.createRange().text));var e=(document.charset||document.characterSet);if(t!=''){location.href='http://translate.google.com/translate_t?text='+t+'&amp;hl=en&amp;langpair=auto|sl&amp;tbb=1&amp;ie='+e;}else{location.href='http://translate.google.com/translate?u='+escape(location.href)+'&amp;hl=en&amp;langpair=auto|sl&amp;tbb=1&amp;ie='+e;};\" onclick=\"alert(document.getElementById('instructions').firstChild.nodeValue);return false;\">Slovenian</a></li>\n";
echo "   <li><a href=\"javascript:var t=((window.getSelection&amp;&amp;window.getSelection())||(document.getSelection&amp;&amp;document.getSelection())||(document.selection&amp;&amp;document.selection.createRange&amp;&amp;document.selection.createRange().text));var e=(document.charset||document.characterSet);if(t!=''){location.href='http://translate.google.com/translate_t?text='+t+'&amp;hl=en&amp;langpair=auto|es&amp;tbb=1&amp;ie='+e;}else{location.href='http://translate.google.com/translate?u='+escape(location.href)+'&amp;hl=en&amp;langpair=auto|es&amp;tbb=1&amp;ie='+e;};\" onclick=\"alert(document.getElementById('instructions').firstChild.nodeValue);return false;\">Spanish</a></li>\n";
echo "   <li><a href=\"javascript:var t=((window.getSelection&amp;&amp;window.getSelection())||(document.getSelection&amp;&amp;document.getSelection())||(document.selection&amp;&amp;document.selection.createRange&amp;&amp;document.selection.createRange().text));var e=(document.charset||document.characterSet);if(t!=''){location.href='http://translate.google.com/translate_t?text='+t+'&amp;hl=en&amp;langpair=auto|sw&amp;tbb=1&amp;ie='+e;}else{location.href='http://translate.google.com/translate?u='+escape(location.href)+'&amp;hl=en&amp;langpair=auto|sw&amp;tbb=1&amp;ie='+e;};\" onclick=\"alert(document.getElementById('instructions').firstChild.nodeValue);return false;\">Swahili</a></li>\n";
echo "   <li><a href=\"javascript:var t=((window.getSelection&amp;&amp;window.getSelection())||(document.getSelection&amp;&amp;document.getSelection())||(document.selection&amp;&amp;document.selection.createRange&amp;&amp;document.selection.createRange().text));var e=(document.charset||document.characterSet);if(t!=''){location.href='http://translate.google.com/translate_t?text='+t+'&amp;hl=en&amp;langpair=auto|sv&amp;tbb=1&amp;ie='+e;}else{location.href='http://translate.google.com/translate?u='+escape(location.href)+'&amp;hl=en&amp;langpair=auto|sv&amp;tbb=1&amp;ie='+e;};\" onclick=\"alert(document.getElementById('instructions').firstChild.nodeValue);return false;\">Swedish</a></li>\n";
echo "   <li><a href=\"javascript:var t=((window.getSelection&amp;&amp;window.getSelection())||(document.getSelection&amp;&amp;document.getSelection())||(document.selection&amp;&amp;document.selection.createRange&amp;&amp;document.selection.createRange().text));var e=(document.charset||document.characterSet);if(t!=''){location.href='http://translate.google.com/translate_t?text='+t+'&amp;hl=en&amp;langpair=auto|th&amp;tbb=1&amp;ie='+e;}else{location.href='http://translate.google.com/translate?u='+escape(location.href)+'&amp;hl=en&amp;langpair=auto|th&amp;tbb=1&amp;ie='+e;};\" onclick=\"alert(document.getElementById('instructions').firstChild.nodeValue);return false;\">Thai</a></li>\n";
echo "   <li><a href=\"javascript:var t=((window.getSelection&amp;&amp;window.getSelection())||(document.getSelection&amp;&amp;document.getSelection())||(document.selection&amp;&amp;document.selection.createRange&amp;&amp;document.selection.createRange().text));var e=(document.charset||document.characterSet);if(t!=''){location.href='http://translate.google.com/translate_t?text='+t+'&amp;hl=en&amp;langpair=auto|tr&amp;tbb=1&amp;ie='+e;}else{location.href='http://translate.google.com/translate?u='+escape(location.href)+'&amp;hl=en&amp;langpair=auto|tr&amp;tbb=1&amp;ie='+e;};\" onclick=\"alert(document.getElementById('instructions').firstChild.nodeValue);return false;\">Turkish</a></li>\n";
echo "   <li><a href=\"javascript:var t=((window.getSelection&amp;&amp;window.getSelection())||(document.getSelection&amp;&amp;document.getSelection())||(document.selection&amp;&amp;document.selection.createRange&amp;&amp;document.selection.createRange().text));var e=(document.charset||document.characterSet);if(t!=''){location.href='http://translate.google.com/translate_t?text='+t+'&amp;hl=en&amp;langpair=auto|uk&amp;tbb=1&amp;ie='+e;}else{location.href='http://translate.google.com/translate?u='+escape(location.href)+'&amp;hl=en&amp;langpair=auto|uk&amp;tbb=1&amp;ie='+e;};\" onclick=\"alert(document.getElementById('instructions').firstChild.nodeValue);return false;\">Ukrainian</a></li>\n";
echo "   <li><a href=\"javascript:var t=((window.getSelection&amp;&amp;window.getSelection())||(document.getSelection&amp;&amp;document.getSelection())||(document.selection&amp;&amp;document.selection.createRange&amp;&amp;document.selection.createRange().text));var e=(document.charset||document.characterSet);if(t!=''){location.href='http://translate.google.com/translate_t?text='+t+'&amp;hl=en&amp;langpair=auto|vi&amp;tbb=1&amp;ie='+e;}else{location.href='http://translate.google.com/translate?u='+escape(location.href)+'&amp;hl=en&amp;langpair=auto|vi&amp;tbb=1&amp;ie='+e;};\" onclick=\"alert(document.getElementById('instructions').firstChild.nodeValue);return false;\">Vietnamese</a></li>\n";
echo "   <li><a href=\"javascript:var t=((window.getSelection&amp;&amp;window.getSelection())||(document.getSelection&amp;&amp;document.getSelection())||(document.selection&amp;&amp;document.selection.createRange&amp;&amp;document.selection.createRange().text));var e=(document.charset||document.characterSet);if(t!=''){location.href='http://translate.google.com/translate_t?text='+t+'&amp;hl=en&amp;langpair=auto|cy&amp;tbb=1&amp;ie='+e;}else{location.href='http://translate.google.com/translate?u='+escape(location.href)+'&amp;hl=en&amp;langpair=auto|cy&amp;tbb=1&amp;ie='+e;};\" onclick=\"alert(document.getElementById('instructions').firstChild.nodeValue);return false;\">Welsh</a></li>\n";
echo "   <li><a href=\"javascript:var t=((window.getSelection&amp;&amp;window.getSelection())||(document.getSelection&amp;&amp;document.getSelection())||(document.selection&amp;&amp;document.selection.createRange&amp;&amp;document.selection.createRange().text));var e=(document.charset||document.characterSet);if(t!=''){location.href='http://translate.google.com/translate_t?text='+t+'&amp;hl=en&amp;langpair=auto|yi&amp;tbb=1&amp;ie='+e;}else{location.href='http://translate.google.com/translate?u='+escape(location.href)+'&amp;hl=en&amp;langpair=auto|yi&amp;tbb=1&amp;ie='+e;};\" onclick=\"alert(document.getElementById('instructions').firstChild.nodeValue);return false;\">Yiddish</a></li>\n";
echo " </ul>\n";
echo " </ul>\n";

echo "<script>\n";
echo " function googleTranslateElementInit() {\n";
echo "  new google.translate.TranslateElement({\n";
echo "    pageLanguage: 'en',\n";
echo "    includedLanguages: 'af,sq,ar,be,bg,ca,zh-CN,zh-TW,hr,cs,da,nl,en,et,tl,fi,fr,gl,de,el,iw,hi,hu,is,id,ga,it,ja,ko,lv,lt,mk,ms,mt,no,fa,pl,pt,ro,ru,sr,sk,sl,es,sw,sv,th,tr,uk,vi,cy,yi'\n";
echo "  }, 'google_translate_element');\n";
echo "}\n";

echo "  </script> \n";
echo "  <script src=\"http://translate.google.com/translate_a/element.js?cb=googleTranslateElementIniti\">hi there</script>\n";

echo "   </div>\n";
echo "   </td></tr>\n";
echo "   <tr><td bgcolor=\"#333333\"><p> </p></td></tr>\n";
echo "   <tr><td bgcolor=\"#AA0000\">\n";
echo "   <br><p> </p>\n";
echo "   <br><p> </p>\n";
echo "   </td></tr></table>\n";
echo "   <!--Optional Banner Start-->\n";
  

echo "   <!--Optional Banner End-->\n";
echo "   <div id=\"sidebar\">\n";
echo "     <div id=\"sidecontent\"> \n";


echo "       <h1>Search </h1>\n";
echo "       <form name=\"sensor_request\" method=\"LINK\" action=\"http://qcn.stanford.edu/search.php\">\n";
echo "       <table><td><tr>\n";
echo "         <input name=\"search_text\" type=\"text\" id=\"search_text\" size=\"20\">\n";
echo "         </tr><tr align=\"center\">\n";
echo "         <input type=\"submit\" name=\"Search\" value=\"Search\">\n";
echo "         </tr></td>\n";
echo "         </table>\n";
echo "         </form>\n"; 

echo "       <h1>Download Now </h1>\n";
echo "       <ul>\n";
echo "         <li><a href=\"http://qcn.stanford.edu/index.php?pg=downloads/index.html#Network\">QCN Network Software </a></li>\n";
echo " 	<li><dd><a href=\"http://boinc.berkeley.edu/index.php?pg=download.html\">(BOINC)</a></p></li></dd>\n";
echo "         <li><a href=\"http://qcn.stanford.edu/index.php?pg=downloads/index.html#Interactive\">QCN Interactive Software</a></li>\n";
echo " 	<li><dd><a href=\"http://qcn.stanford.edu/index.php?pg=downloads/index.html#Interactive\">(QCNLive)</a></li></dd>\n";
echo "         <li><a href=\"http://qcn.stanford.edu/index.php?pg=downloads/index.html#USB_Drivers\">USB Sensor Drivers</a></li>\n";
echo "         <li><a href=\"http://qcn.stanford.edu/index.php?pg=manuals/index.html\">Manuals/Instructions</a></li>\n";
echo "       </ul><br>\n";

echo "       <h1>Request A Sensor</h1>\n";
echo "       <ul>\n";
echo "         <a href=\"http://qcn.stanford.edu/index.php?pg=learning/requests.html#K12\"><li>K-12 Program</li></a>\n";
echo "         <a href=\"http://qcn.stanford.edu/index.php?pg=learning/requests.html#Purchase\"><li>Purchase a Sensor</li></a>\n";
echo "         <a href=\"http://qcn.stanford.edu/index.php?pg=learning/requests.html#Donate\"><li>Give Sensors to Schools</li></a>\n";
echo "       </ul>\n";
echo "       <br>\n";

echo "       <h1>Recent News</h1>\n";
echo "       <ul>\n";

include("/var/www/boinc/sensor/html/inc/some_news.inc");
echo "       <br>\n";

echo "       </ul>\n";


echo " <map name=\"trigger_latest_w\">\n";
echo "         <area shape=\"rect\" coords=\"0,2,225,232\" href=\"http://qcn.stanford.edu/sensor/maptrig.php?cx=38&cy=-120&timeint=W\">\n";

echo "         <area shape=\"rect\" coords=\"2,236,228,511\" href=\"http://qcn.stanford.edu/sensor/maptrig.php?cx=-20&cy=-120&timeint=W\">\n";
echo "         <area shape=\"rect\" coords=\"227,3,428,234\" href=\"http://qcn.stanford.edu/sensor/maptrig.php?cx=38&cy=-70&timeint=W\">\n";
echo "         <area shape=\"rect\" coords=\"231,238,442,510\" href=\"http://qcn.stanford.edu/sensor/maptrig.php?cx=-20&cy=-70&timeint=W\">\n";
echo "         <area shape=\"rect\" coords=\"430,3,605,237\" href=\"http://qcn.stanford.edu/sensor/maptrig.php?cx=50&cy=1&timeint=W\">\n";
echo "         <area shape=\"rect\" coords=\"445,241,732,510\" href=\"http://qcn.stanford.edu/sensor/maptrig.php?cx=-10&cy=5&timeint=W\">\n";
echo "         <area shape=\"rect\" coords=\"609,3,803,239\" href=\"http://qcn.stanford.edu/sensor/maptrig.php?cx=38&cy=80&timeint=W\">\n";
echo "         <area shape=\"rect\" coords=\"735,244,1022,511\" href=\"http://qcn.stanford.edu/sensor/maptrig.php?cx=-20&cy=140&timeint=W\">\n";
echo "         <area shape=\"rect\" coords=\"806,3,1021,243\" href=\"http://qcn.stanford.edu/sensor/maptrig.php?cx=38&cy=140&timeint=W\">\n";
echo " </map>\n";

echo " <h1 id=\"qcnmap\">QCN Sensor Map</h1>\n";
echo " <p><img src=\"http://qcn.stanford.edu/sensor/img/trigger_latest_w.jpg\" usemap=\"#trigger_latest_w\" border=\"0\" width=\"140\">\n";

echo " <h1 id=\"qcngrowth\">QCN Growth</h1>\n";
echo " <p><a href=\"http://qcn.stanford.edu/sensor/img/weekly.png\"><img src=\"http://qcn.stanford.edu/sensor/img/weekly.png\" border=\"0\" width=\"140\"></a>\n";

echo " <h1 id=\"sponsors\">QCN Sponsors</h1>\n";
echo " <p><a href=\"http://www.nsf.gov\"><img src=\"http://qcn.stanford.edu/images/nsf_logo.jpg\" width=\"100\"></img></a>\n";

echo " <p><a href=\"http://www.scec.org\"><img src=\"http://qcn.stanford.edu/images/scec_logo.jpg\" width=\"100\"></img></a>\n";

echo " <p><a href=\"http://www.iris.edu\"><img src=\"http://qcn.stanford.edu/images/iris_logo.png\" width=\"100\"></img></a>\n";



echo "     </div>\n";


echo "   </div>\n";


echo "   <div id=\"content\">\n";
echo "     <!--Optional Breadcrumb Start-->\n";
   
echo "     <!--Optional Breadcrumb End-->\n";

  
echo "     <div id=\"maincontent\">\n";

}

function page_end(){
echo "    </div>\n";
echo "    <br style=\"clear: both;\" />\n";
echo "  </div>\n";
echo "  <div id=\"footer\"> \n";
echo "    <ul>\n";
echo "      <li><a href=\"http://qcn.stanford.edu/index.php?pg=\">QCN Home</a></li>\n";
echo "      <li><a href=\"http://qcn.stanford.edu/index.php?pg=about/contact.php\">Contact</a></li><li class=\"last\"><a href=\"http://qcn.stanford.edu/index.php?pg=downloads/\">Download Now </a></li> \n";

echo "    </ul>\n";
echo "  </div>\n";
echo "</div>\n";
echo "<div id=\"copyright\" class=\"vcard\"> <!-- InstanceBeginEditable name=\"copyright\" -->&copy; <span class=\"fn org\">Quake-Catcher Network </span>.  All Rights Reserved.<!-- InstanceEndEditable --></div>\n";

echo "</body>\n";
echo "</html>\n";
}
?>
