#############################################################################
# Makefile for building: 
# Generated by qmake (3.0) (Qt 5.0.0) on: Sat Jan 5 16:01:48 2013
# Project:  QCNLive.pro
# Template: app
# Command: /Developer/Qt5.0.0/5.0.0/clang_64/bin/qmake -spec /Developer/Qt5.0.0/5.0.0/clang_64/mkspecs/macx-xcode -o QCNLive.xcodeproj/project.pbxproj QCNLive.pro
#############################################################################

MAKEFILE      = project.pbxproj

QMAKE    = /Developer/Qt5.0.0/5.0.0/clang_64/bin/qmake
QCNLive.xcodeproj/project.pbxproj: QCNLive.pro /Developer/Qt5.0.0/5.0.0/clang_64/mkspecs/macx-xcode/qmake.conf /Developer/Qt5.0.0/5.0.0/clang_64/mkspecs/features/spec_pre.prf \
		/Developer/Qt5.0.0/5.0.0/clang_64/mkspecs/qdevice.pri \
		/Developer/Qt5.0.0/5.0.0/clang_64/mkspecs/features/device_config.prf \
		/Developer/Qt5.0.0/5.0.0/clang_64/mkspecs/common/shell-unix.conf \
		/Developer/Qt5.0.0/5.0.0/clang_64/mkspecs/common/unix.conf \
		/Developer/Qt5.0.0/5.0.0/clang_64/mkspecs/common/mac.conf \
		/Developer/Qt5.0.0/5.0.0/clang_64/mkspecs/common/gcc-base.conf \
		/Developer/Qt5.0.0/5.0.0/clang_64/mkspecs/common/gcc-base-macx.conf \
		/Developer/Qt5.0.0/5.0.0/clang_64/mkspecs/common/g++-base.conf \
		/Developer/Qt5.0.0/5.0.0/clang_64/mkspecs/common/g++-macx.conf \
		/Developer/Qt5.0.0/5.0.0/clang_64/mkspecs/common/mac-minimum-version.conf \
		/Developer/Qt5.0.0/5.0.0/clang_64/mkspecs/qconfig.pri \
		/Developer/Qt5.0.0/5.0.0/clang_64/mkspecs/modules/qt_lib_bootstrap.pri \
		/Developer/Qt5.0.0/5.0.0/clang_64/mkspecs/modules/qt_lib_clucene.pri \
		/Developer/Qt5.0.0/5.0.0/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		/Developer/Qt5.0.0/5.0.0/clang_64/mkspecs/modules/qt_lib_core.pri \
		/Developer/Qt5.0.0/5.0.0/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		/Developer/Qt5.0.0/5.0.0/clang_64/mkspecs/modules/qt_lib_designer.pri \
		/Developer/Qt5.0.0/5.0.0/clang_64/mkspecs/modules/qt_lib_designercomponents.pri \
		/Developer/Qt5.0.0/5.0.0/clang_64/mkspecs/modules/qt_lib_gui.pri \
		/Developer/Qt5.0.0/5.0.0/clang_64/mkspecs/modules/qt_lib_help.pri \
		/Developer/Qt5.0.0/5.0.0/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		/Developer/Qt5.0.0/5.0.0/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/Developer/Qt5.0.0/5.0.0/clang_64/mkspecs/modules/qt_lib_network.pri \
		/Developer/Qt5.0.0/5.0.0/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		/Developer/Qt5.0.0/5.0.0/clang_64/mkspecs/modules/qt_lib_platformsupport.pri \
		/Developer/Qt5.0.0/5.0.0/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		/Developer/Qt5.0.0/5.0.0/clang_64/mkspecs/modules/qt_lib_qml.pri \
		/Developer/Qt5.0.0/5.0.0/clang_64/mkspecs/modules/qt_lib_qmldevtools.pri \
		/Developer/Qt5.0.0/5.0.0/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		/Developer/Qt5.0.0/5.0.0/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools.pri \
		/Developer/Qt5.0.0/5.0.0/clang_64/mkspecs/modules/qt_lib_quick.pri \
		/Developer/Qt5.0.0/5.0.0/clang_64/mkspecs/modules/qt_lib_quickparticles.pri \
		/Developer/Qt5.0.0/5.0.0/clang_64/mkspecs/modules/qt_lib_script.pri \
		/Developer/Qt5.0.0/5.0.0/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		/Developer/Qt5.0.0/5.0.0/clang_64/mkspecs/modules/qt_lib_sql.pri \
		/Developer/Qt5.0.0/5.0.0/clang_64/mkspecs/modules/qt_lib_svg.pri \
		/Developer/Qt5.0.0/5.0.0/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		/Developer/Qt5.0.0/5.0.0/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		/Developer/Qt5.0.0/5.0.0/clang_64/mkspecs/modules/qt_lib_v8.pri \
		/Developer/Qt5.0.0/5.0.0/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		/Developer/Qt5.0.0/5.0.0/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/Developer/Qt5.0.0/5.0.0/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		/Developer/Qt5.0.0/5.0.0/clang_64/mkspecs/modules/qt_lib_xml.pri \
		/Developer/Qt5.0.0/5.0.0/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/Developer/Qt5.0.0/5.0.0/clang_64/mkspecs/features/qt_functions.prf \
		/Developer/Qt5.0.0/5.0.0/clang_64/mkspecs/features/qt_config.prf \
		/Developer/Qt5.0.0/5.0.0/clang_64/mkspecs/macx-xcode/qmake.conf \
		/Developer/Qt5.0.0/5.0.0/clang_64/mkspecs/features/spec_post.prf \
		/Developer/Qt5.0.0/5.0.0/clang_64/mkspecs/features/exclusive_builds.prf \
		/Developer/Qt5.0.0/5.0.0/clang_64/mkspecs/features/default_pre.prf \
		/Developer/Qt5.0.0/5.0.0/clang_64/mkspecs/features/unix/default_pre.prf \
		/Developer/Qt5.0.0/5.0.0/clang_64/mkspecs/features/mac/default_pre.prf \
		/Developer/Qt5.0.0/5.0.0/clang_64/mkspecs/features/release.prf \
		/Developer/Qt5.0.0/5.0.0/clang_64/mkspecs/features/default_post.prf \
		/Developer/Qt5.0.0/5.0.0/clang_64/mkspecs/features/mac/default_post.prf \
		/Developer/Qt5.0.0/5.0.0/clang_64/mkspecs/features/mac/objective_c.prf \
		/Developer/Qt5.0.0/5.0.0/clang_64/mkspecs/features/shared.prf \
		/Developer/Qt5.0.0/5.0.0/clang_64/mkspecs/features/warn_on.prf \
		/Developer/Qt5.0.0/5.0.0/clang_64/mkspecs/features/qt.prf \
		/Developer/Qt5.0.0/5.0.0/clang_64/mkspecs/features/resources.prf \
		/Developer/Qt5.0.0/5.0.0/clang_64/mkspecs/features/moc.prf \
		/Developer/Qt5.0.0/5.0.0/clang_64/mkspecs/features/unix/opengl.prf \
		/Developer/Qt5.0.0/5.0.0/clang_64/mkspecs/features/unix/thread.prf \
		/Developer/Qt5.0.0/5.0.0/clang_64/mkspecs/features/mac/rez.prf \
		/Developer/Qt5.0.0/5.0.0/clang_64/mkspecs/features/mac/sdk.prf \
		/Developer/Qt5.0.0/5.0.0/clang_64/mkspecs/features/testcase_targets.prf \
		/Developer/Qt5.0.0/5.0.0/clang_64/mkspecs/features/exceptions.prf \
		/Developer/Qt5.0.0/5.0.0/clang_64/mkspecs/features/yacc.prf \
		/Developer/Qt5.0.0/5.0.0/clang_64/mkspecs/features/lex.prf \
		../QCNLive.pro \
		/Developer/Qt5.0.0/5.0.0/clang_64/lib/QtGui.framework/QtGui.prl \
		/Developer/Qt5.0.0/5.0.0/clang_64/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -spec /Developer/Qt5.0.0/5.0.0/clang_64/mkspecs/macx-xcode -o QCNLive.xcodeproj/project.pbxproj QCNLive.pro
/Developer/Qt5.0.0/5.0.0/clang_64/mkspecs/features/spec_pre.prf:
/Developer/Qt5.0.0/5.0.0/clang_64/mkspecs/qdevice.pri:
/Developer/Qt5.0.0/5.0.0/clang_64/mkspecs/features/device_config.prf:
/Developer/Qt5.0.0/5.0.0/clang_64/mkspecs/common/shell-unix.conf:
/Developer/Qt5.0.0/5.0.0/clang_64/mkspecs/common/unix.conf:
/Developer/Qt5.0.0/5.0.0/clang_64/mkspecs/common/mac.conf:
/Developer/Qt5.0.0/5.0.0/clang_64/mkspecs/common/gcc-base.conf:
/Developer/Qt5.0.0/5.0.0/clang_64/mkspecs/common/gcc-base-macx.conf:
/Developer/Qt5.0.0/5.0.0/clang_64/mkspecs/common/g++-base.conf:
/Developer/Qt5.0.0/5.0.0/clang_64/mkspecs/common/g++-macx.conf:
/Developer/Qt5.0.0/5.0.0/clang_64/mkspecs/common/mac-minimum-version.conf:
/Developer/Qt5.0.0/5.0.0/clang_64/mkspecs/qconfig.pri:
/Developer/Qt5.0.0/5.0.0/clang_64/mkspecs/modules/qt_lib_bootstrap.pri:
/Developer/Qt5.0.0/5.0.0/clang_64/mkspecs/modules/qt_lib_clucene.pri:
/Developer/Qt5.0.0/5.0.0/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
/Developer/Qt5.0.0/5.0.0/clang_64/mkspecs/modules/qt_lib_core.pri:
/Developer/Qt5.0.0/5.0.0/clang_64/mkspecs/modules/qt_lib_declarative.pri:
/Developer/Qt5.0.0/5.0.0/clang_64/mkspecs/modules/qt_lib_designer.pri:
/Developer/Qt5.0.0/5.0.0/clang_64/mkspecs/modules/qt_lib_designercomponents.pri:
/Developer/Qt5.0.0/5.0.0/clang_64/mkspecs/modules/qt_lib_gui.pri:
/Developer/Qt5.0.0/5.0.0/clang_64/mkspecs/modules/qt_lib_help.pri:
/Developer/Qt5.0.0/5.0.0/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
/Developer/Qt5.0.0/5.0.0/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
/Developer/Qt5.0.0/5.0.0/clang_64/mkspecs/modules/qt_lib_network.pri:
/Developer/Qt5.0.0/5.0.0/clang_64/mkspecs/modules/qt_lib_opengl.pri:
/Developer/Qt5.0.0/5.0.0/clang_64/mkspecs/modules/qt_lib_platformsupport.pri:
/Developer/Qt5.0.0/5.0.0/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
/Developer/Qt5.0.0/5.0.0/clang_64/mkspecs/modules/qt_lib_qml.pri:
/Developer/Qt5.0.0/5.0.0/clang_64/mkspecs/modules/qt_lib_qmldevtools.pri:
/Developer/Qt5.0.0/5.0.0/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
/Developer/Qt5.0.0/5.0.0/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools.pri:
/Developer/Qt5.0.0/5.0.0/clang_64/mkspecs/modules/qt_lib_quick.pri:
/Developer/Qt5.0.0/5.0.0/clang_64/mkspecs/modules/qt_lib_quickparticles.pri:
/Developer/Qt5.0.0/5.0.0/clang_64/mkspecs/modules/qt_lib_script.pri:
/Developer/Qt5.0.0/5.0.0/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
/Developer/Qt5.0.0/5.0.0/clang_64/mkspecs/modules/qt_lib_sql.pri:
/Developer/Qt5.0.0/5.0.0/clang_64/mkspecs/modules/qt_lib_svg.pri:
/Developer/Qt5.0.0/5.0.0/clang_64/mkspecs/modules/qt_lib_testlib.pri:
/Developer/Qt5.0.0/5.0.0/clang_64/mkspecs/modules/qt_lib_uitools.pri:
/Developer/Qt5.0.0/5.0.0/clang_64/mkspecs/modules/qt_lib_v8.pri:
/Developer/Qt5.0.0/5.0.0/clang_64/mkspecs/modules/qt_lib_webkit.pri:
/Developer/Qt5.0.0/5.0.0/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
/Developer/Qt5.0.0/5.0.0/clang_64/mkspecs/modules/qt_lib_widgets.pri:
/Developer/Qt5.0.0/5.0.0/clang_64/mkspecs/modules/qt_lib_xml.pri:
/Developer/Qt5.0.0/5.0.0/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
/Developer/Qt5.0.0/5.0.0/clang_64/mkspecs/features/qt_functions.prf:
/Developer/Qt5.0.0/5.0.0/clang_64/mkspecs/features/qt_config.prf:
/Developer/Qt5.0.0/5.0.0/clang_64/mkspecs/macx-xcode/qmake.conf:
/Developer/Qt5.0.0/5.0.0/clang_64/mkspecs/features/spec_post.prf:
/Developer/Qt5.0.0/5.0.0/clang_64/mkspecs/features/exclusive_builds.prf:
/Developer/Qt5.0.0/5.0.0/clang_64/mkspecs/features/default_pre.prf:
/Developer/Qt5.0.0/5.0.0/clang_64/mkspecs/features/unix/default_pre.prf:
/Developer/Qt5.0.0/5.0.0/clang_64/mkspecs/features/mac/default_pre.prf:
/Developer/Qt5.0.0/5.0.0/clang_64/mkspecs/features/release.prf:
/Developer/Qt5.0.0/5.0.0/clang_64/mkspecs/features/default_post.prf:
/Developer/Qt5.0.0/5.0.0/clang_64/mkspecs/features/mac/default_post.prf:
/Developer/Qt5.0.0/5.0.0/clang_64/mkspecs/features/mac/objective_c.prf:
/Developer/Qt5.0.0/5.0.0/clang_64/mkspecs/features/shared.prf:
/Developer/Qt5.0.0/5.0.0/clang_64/mkspecs/features/warn_on.prf:
/Developer/Qt5.0.0/5.0.0/clang_64/mkspecs/features/qt.prf:
/Developer/Qt5.0.0/5.0.0/clang_64/mkspecs/features/resources.prf:
/Developer/Qt5.0.0/5.0.0/clang_64/mkspecs/features/moc.prf:
/Developer/Qt5.0.0/5.0.0/clang_64/mkspecs/features/unix/opengl.prf:
/Developer/Qt5.0.0/5.0.0/clang_64/mkspecs/features/unix/thread.prf:
/Developer/Qt5.0.0/5.0.0/clang_64/mkspecs/features/mac/rez.prf:
/Developer/Qt5.0.0/5.0.0/clang_64/mkspecs/features/mac/sdk.prf:
/Developer/Qt5.0.0/5.0.0/clang_64/mkspecs/features/testcase_targets.prf:
/Developer/Qt5.0.0/5.0.0/clang_64/mkspecs/features/exceptions.prf:
/Developer/Qt5.0.0/5.0.0/clang_64/mkspecs/features/yacc.prf:
/Developer/Qt5.0.0/5.0.0/clang_64/mkspecs/features/lex.prf:
../QCNLive.pro:
/Developer/Qt5.0.0/5.0.0/clang_64/lib/QtGui.framework/QtGui.prl:
/Developer/Qt5.0.0/5.0.0/clang_64/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -spec /Developer/Qt5.0.0/5.0.0/clang_64/mkspecs/macx-xcode -o QCNLive.xcodeproj/project.pbxproj QCNLive.pro

qmake_all: FORCE

