#!/bin/sh
#if have 2nd arg, it forces boinc build, 3rd arg forced boinc Mac PPC build
if ( test "$1" = "" || test "$2" = "") then
   echo Usage:  ./deploy VERSION_NUMBER_NCI VERSION_NUMBER_REGULAR
   echo 'NCI should usually be one higher than regular version number'
   exit 1
fi
if (test $3) then
   rm -rf boinc
   ./getboinc
#cd boinc/mac_build
#chmod uog+rx *.sh
#./BuildMacBOINC.sh

   cd boinc
#   cd boinc/mac_build
#   if (test $3) then
#      xcodebuild -project boinc.xcodeproj -configuration i386_Deployment clean build
#   else
#      xcodebuild -project boinc.xcodeproj -configuration i386_Deployment clean build
#   fi
   ./_autosetup
if ( test "`uname -s`" = "Darwin" ) then
   ./configure --with-apple-opengl-framework --disable-fcgi --disable-manager --disable-client --disable-server
else
#  echo "don't forget the Linux vpn: sudo vpnclient connect stanford"
  ./configure --disable-fcgi --disable-manager --disable-client --disable-server
fi
   make clean
   make
#   g++ boinc/api/macglutfix.m -c -o boinc/api/macglutfix.o
#   cd ../../
  cd ../
fi
# at least update boinc cvs?
svn update boinc
cd boinc
make distclean
./_autosetup
if ( test "`uname -s`" = "Darwin" ) then
   ./configure --with-apple-opengl-framework --disable-fcgi --disable-manager --disable-client --disable-server
else
   echo "don't forget the Linux vpn: sudo vpnclient connect stanford"
   ./configure --disable-fcgi --disable-manager --disable-client --disable-server
fi
make clean
make
cd ..
# don't need to build ntp often, just when making the executables to distribute
#tar xzf ntp-4.2.4p5.tar.gz
#cd ntp-4.2.4p5
#./configure --disable-shared --without-crypto
#make clean && make
#cd ../
./set-version $1
make distclean
./_autosetup
if ( test "`uname -s`" = "Darwin" ) then
./configure --with-apple-opengl-framework --enable-client-release --disable-server
else
./configure --enable-client-release --disable-server
fi
make clean
make
#if ( test "`uname -s`" = "Darwin" ) then
#cd client/qcnlive
#if ( test "`uname -p`" = "i386" ) then
#xcodebuild -project qcnlive.xcodeproj -configuration 'Release' clean build
#else
#xcodebuild -project qcnlive.xcodeproj -configuration 'Release PowerPC' clean build
#fi
#fi
#cd ../../
cd client/bin
./deploy $1 $2
