#!/bin/sh
if ( test "$1" = "" || test "$2" = "") then
   echo Usage:  ./build VERSION_NUMBER_NCI VERSION_NUMBER_REGULAR
   echo 'NCI should usually be one higher than regular version number'
   exit 1
fi
if (test $3) then
   rm -rf boinc
   ./getboinc
else
   # at least update boinc cvs?
   svn update boinc
fi
cd boinc
if ( test "`uname -s`" = "Darwin" ) then
   cd zip
   xcodebuild -project boinc_zip.xcodeproj -target boinc_zip -configuration Release clean build
   cd ../mac_build
   xcodebuild -project boinc.xcodeproj -target api_libboinc -configuration Deployment clean build
   xcodebuild -project boinc.xcodeproj -target gfx2libboinc -configuration Deployment clean build
   xcodebuild -project boinc.xcodeproj -target libboinc -configuration Deployment clean build
   cd ../
else
 #  echo "don't forget the Linux vpn: sudo vpnclient connect stanford"
  ./_autosetup
  ./configure --disable-fcgi --disable-manager --disable-client --disable-server
   make clean && make
fi
cd ../
# don't need to build ntp often, just when making the executables to distribute
#tar xzf ntp-4.2.4p5.tar.gz
#cd ntp-4.2.4p5
#./configure --disable-shared --without-crypto
#make clean && make
#cd ../
./set-version $1
make distclean
./_autosetup
if ( test "`uname -s`" = "Darwin" ) then
./configure --with-apple-opengl-framework --enable-client-release --disable-server
else
./configure --enable-client-release --disable-server
fi
make clean
make
#if ( test "`uname -s`" = "Darwin" ) then
#cd client/qcnlive
#if ( test "`uname -p`" = "i386" ) then
#xcodebuild -project qcnlive.xcodeproj -configuration 'Release' clean build
#else
#xcodebuild -project qcnlive.xcodeproj -configuration 'Release PowerPC' clean build
#fi
#fi
#cd ../../
cd client/bin
./deploy $1 $2
