#!/bin/sh
if (test $1) then
   rm -rf boinc
   ./getboinc
fi
cd boinc
cp -rf ../server/boincmods/* .
make distclean
./_autosetup
./configure
make
cd sched
mv cgi cgi.orig
mv file_upload_handler file_upload_handler.orig
make fcgi
make fcgi_file_upload_handler
mv fcgi cgi
mv fcgi_file_upload_handler file_upload_handler
strip cgi
strip file_upload_handler
cd ../../
echo "If built OK, go to boinc/tools and run ./upgrade"
