#!/bin/sh
if ( test "$1" = "") then
   echo "Usage:  ./build VERSION_NUMBER [all]"
   exit 1
fi
./set-version $1
if (test "$2" = "all" || test "$3" = "all") then
   ./getboinc
else
   # at least update boinc cvs?
   cd ..
   svn update boinc
   cd qcn
fi
if ( test "`uname -s`" = "Darwin" ) then
  cp config.h.mac config.h
  chmod uog+rx build.mac
  make distclean
  ./_autosetup
  ./configure --disable-client --disable-server --disable-manager --disable-fcgi
  cp config.h.mac config.h
  ./build.mac $2 $3
else
  make distclean
  cd zlib-1.2.5
  ./configure
  make clean && make
  cd ..
  cd jpeg-6b
  ./configure
  make clean && make
  cd ../boinc
  make distclean
  ./_autosetup
  ./configure --enable-client-release --disable-client --disable-server --disable-manager --disable-fcgi
  make clean && make
  cd ../qcn
  ./_autosetup
  ./configure --enable-client-release --disable-server
  make clean
  make
fi
cd client/bin
./deploy $1 $2 $3
