#!/bin/bash
# note -- as you edit a file on the server, add a line here to get it locally, also don't forget to add it to subversion (& commit)
scp carlgt1@qcn-web:/var/www/qcnwp/wp-content/plugins/external-database-authentication/* qcnwp/external-database-authentication
scp carlgt1@qcn-web:/var/www/qcn/ramp/index.php ../ramp/
scp carlgt1@qcn-web:/var/www/boinc/sensor/project_files.xml ../config/
scp carlgt1@qcn-web:/var/www/boinc/sensor/gui_urls.xml ../config/
scp carlgt1@qcn-web:/var/www/boinc/sensor/bin/generate_maptrig.sh ../config/
scp carlgt1@qcn-web:/usr/local/apache2/conf/extra/httpd-ssl.conf ../config/
scp carlgt1@qcn-web:/var/www/boinc/sensor/bin/clean_tmpdata.sh ../config/
scp carlgt1@qcn-web:/usr/local/apache2/conf/httpd.conf ../config/
scp carlgt1@qcn-web:/usr/local/apache2/conf/drupal.conf ../config/
scp carlgt1@qcn-web:/etc/init.d/httpd ../config/
scp carlgt1@qcn-web:/var/www/boinc/sensor/html/inc/cache.inc inc/
scp carlgt1@qcn-web:/var/www/boinc/sensor/html/inc/sqlquerystring.inc inc/
scp carlgt1@qcn-web:/var/www/boinc/sensor/html/inc/db_ops.inc inc/
scp carlgt1@qcn-web:/var/www/boinc/sensor/html/inc/forum.inc inc/
scp carlgt1@qcn-web:/var/www/boinc/sensor/html/inc/host.inc inc/
scp carlgt1@qcn-web:/var/www/boinc/sensor/html/inc/phoogle.inc inc/
scp carlgt1@qcn-web:/var/www/boinc/sensor/html/inc/prefs.inc inc/
scp carlgt1@qcn-web:/var/www/boinc/sensor/html/inc/user.inc inc/
scp carlgt1@qcn-web:/var/www/boinc/sensor/html/inc/distance.inc inc/
scp carlgt1@qcn-web:/var/www/boinc/sensor/html/inc/util.inc inc/
scp carlgt1@qcn-web:/var/www/boinc/sensor/html/inc/utils.inc inc/
scp carlgt1@qcn-web:/var/www/boinc/sensor/html/inc/google_translate.inc inc/
scp carlgt1@qcn-web:/var/www/boinc/sensor/html/project/common.inc project/
scp carlgt1@qcn-web:/var/www/boinc/sensor/html/project/csh.env project/
scp carlgt1@qcn-web:/var/www/boinc/sensor/html/project/bash.env project/
scp carlgt1@qcn-web:/var/www/boinc/sensor/html/project/cache_parameters.inc project/
scp carlgt1@qcn-web:/var/www/boinc/sensor/html/project/project.inc project/
scp carlgt1@qcn-web:/var/www/boinc/sensor/html/project/project_news.inc project/
scp carlgt1@qcn-web:/var/www/boinc/sensor/html/project/project_specific_prefs.inc project/
scp carlgt1@qcn-web:/var/www/boinc/sensor/html/project/plate_boundary.inc project/
scp carlgt1@qcn-web:/var/www/boinc/sensor/config.xml ../config/
cat ../config/config.xml | grep -v 'NQu' > cc.txt
mv cc.txt ../config/config.xml
scp carlgt1@qcn-web:/var/www/boinc/continual/config.xml ../config/continual_config.xml
cat ../config/continual_config.xml | grep -v 'NQu' > cc.txt
mv cc.txt ../config/continual_config.xml
scp carlgt1@qcn-web:/var/www/boinc/sensor/html/user/forum_rate.php user/
scp carlgt1@qcn-web:/var/www/boinc/sensor/html/user/REDS_list_signup.php user/
scp carlgt1@qcn-web:/var/www/boinc/sensor/html/user/ramp_signup.php user/
scp carlgt1@qcn-web:/var/www/boinc/sensor/html/user/rampreg_signup.php user/
scp carlgt1@qcn-web:/var/www/boinc/sensor/html/user/login_form.php user/
scp carlgt1@qcn-web:/var/www/boinc/sensor/html/user/ramp_map.php user/
scp carlgt1@qcn-web:/var/www/boinc/sensor/html/user/account_finish.php user/
scp carlgt1@qcn-web:/var/www/boinc/sensor/html/user/account_finish_action.php user/
scp carlgt1@qcn-web:/var/www/boinc/sensor/html/user/create_account.php user/
scp carlgt1@qcn-web:/var/www/boinc/sensor/html/user/create_account_form.php user/
scp carlgt1@qcn-web:/var/www/boinc/sensor/html/user/info.php user/
scp carlgt1@qcn-web:/var/www/boinc/sensor/html/user/edit_host_info_form.php user/
scp carlgt1@qcn-web:/var/www/boinc/sensor/html/user/edit_host_info_action.php user/
scp carlgt1@qcn-web:/var/www/boinc/sensor/html/user/edit_user_info_form.php user/
scp carlgt1@qcn-web:/var/www/boinc/sensor/html/user/index.php user/
scp carlgt1@qcn-web:/var/www/boinc/sensor/html/user/forum_index.php user/
scp carlgt1@qcn-web:/var/www/boinc/sensor/html/user/rss_main.php user/
scp carlgt1@qcn-web:/var/www/boinc/sensor/html/user/all_news.php user/
scp carlgt1@qcn-web:/var/www/boinc/sensor/html/user/maptrig.php user/
scp carlgt1@qcn-web:/var/www/boinc/sensor/html/user/maptrigtime.php user/
scp carlgt1@qcn-web:/var/www/boinc/sensor/html/user/results.php user/
scp carlgt1@qcn-web:/var/www/boinc/sensor/html/user/qcn.css user/
scp carlgt1@qcn-web:/var/www/boinc/sensor/html/user/qcn_orig.css user/
scp carlgt1@qcn-web:/var/www/boinc/sensor/html/user/qcn_wordpress.css user/
scp carlgt1@qcn-web:/var/www/boinc/sensor/html/user/show_host_detail.php user/
scp carlgt1@qcn-web:/var/www/boinc/sensor/html/user/server_status.php user/
scp carlgt1@qcn-web:/var/www/boinc/sensor/html/user/trigger.php user/
scp carlgt1@qcn-web:/var/www/boinc/sensor/html/user/show_user.php user/
scp carlgt1@qcn-web:/var/www/boinc/sensor/html/user/ramp.php user/
scp carlgt1@qcn-web:/var/www/boinc/sensor/html/user/trdl.php user/
scp carlgt1@qcn-web:/var/www/boinc/sensor/html/user/trdlreq.php user/
scp carlgt1@qcn-web:/var/www/boinc/sensor/html/user/calendarDateInput.js user/
scp carlgt1@qcn-web:/var/www/boinc/sensor/html/user/calendar.jpg user/
scp carlgt1@qcn-web:/var/www/boinc/sensor/html/ops/mass_email.php ops/
scp carlgt1@qcn-web:/var/www/boinc/sensor/html/ops/db_form.php ops/
scp carlgt1@qcn-web:/var/www/boinc/sensor/html/ops/db_action.php ops/
scp carlgt1@qcn-web:/var/www/boinc/sensor/html/ops/index.php ops/
scp carlgt1@qcn-web:/var/www/boinc/sensor/html/ops/next.gif ops/
scp carlgt1@qcn-web:/var/www/boinc/sensor/html/ops/prev.gif ops/
scp carlgt1@qcn-web:/var/www/boinc/sensor/html/ops/dbinfo.php ops/
scp carlgt1@qcn-web:/var/www/boinc/sensor/html/ops/generate_maptrig.php ops/
scp carlgt1@qcn-web:/var/www/boinc/sensor/html/ops/weekly-host.php ops/
scp carlgt1@qcn-web:/var/www/boinc/sensor/html/ops/.htaccess ops/
scp carlgt1@qcn-web:/var/www/boinc/sensor/html/inc/earthquake_email.inc inc/
scp carlgt1@qcn-web:/var/www/boinc/sensor/html/inc/email.inc inc/
scp carlgt1@qcn-web:/var/www/boinc/sensor/html/user/earthquake_email.php user/

#continual
scp carlgt1@qcn-web:/var/www/boinc/continual/html/ops/generate_maptrig.php continual/ops/
scp carlgt1@qcn-web:/var/www/boinc/continual/html/inc/db.inc continual/inc/
scp carlgt1@qcn-web:/var/www/boinc/continual/html/inc/prefs.inc continual/inc/
scp carlgt1@qcn-web:/var/www/boinc/continual/html/inc/utils.inc continual/inc/
scp carlgt1@qcn-web:/var/www/boinc/continual/html/inc/util.inc continual/inc/
scp carlgt1@qcn-web:/var/www/boinc/continual/html/inc/user.inc continual/inc/
scp carlgt1@qcn-web:/var/www/boinc/continual/html/inc/host.inc continual/inc/
scp carlgt1@qcn-web:/var/www/boinc/continual/html/inc/cache.inc continual/inc/
scp carlgt1@qcn-web:/var/www/boinc/continual/html/inc/email.inc continual/inc/
scp carlgt1@qcn-web:/var/www/boinc/continual/html/project/common.inc continual/project/
scp carlgt1@qcn-web:/var/www/boinc/continual/html/project/project.inc continual/project/
scp carlgt1@qcn-web:/var/www/boinc/continual/html/project/project_specific_prefs.inc continual/project/
scp carlgt1@qcn-web:/var/www/boinc/continual/html/user/calendar.jpg continual/user/
scp carlgt1@qcn-web:/var/www/boinc/continual/html/user/calendarDateInput.js continual/user/
scp carlgt1@qcn-web:/var/www/boinc/continual/html/user/prefs.php continual/user/
scp carlgt1@qcn-web:/var/www/boinc/continual/html/user/edit_host_info_form.php continual/user/
scp carlgt1@qcn-web:/var/www/boinc/continual/html/user/edit_host_info_action.php continual/user/
scp carlgt1@qcn-web:/var/www/boinc/continual/html/user/maptrig.php continual/user/
scp carlgt1@qcn-web:/var/www/boinc/continual/html/user/maptrigtime.php continual/user/
scp carlgt1@qcn-web:/var/www/boinc/continual/html/user/account_finish.php continual/user/
scp carlgt1@qcn-web:/var/www/boinc/continual/html/user/account_finish_action.php continual/user/
scp carlgt1@qcn-web:/var/www/boinc/continual/html/user/index.php continual/user/

# earthquake scripts etc
scp carlgt1@qcn-web:/var/www/qcn/earthquakes/earthquake_stats.php qcn/earthquakes/
scp carlgt1@qcn-web:/var/www/qcn/earthquakes/events.xy qcn/earthquakes/
scp carlgt1@qcn-web:/var/www/qcn/earthquakes/index_jday.php qcn/earthquakes/
scp carlgt1@qcn-web:/var/www/qcn/earthquakes/index.php qcn/earthquakes/
scp carlgt1@qcn-web:/var/www/qcn/earthquakes/latency.php qcn/earthquakes/
scp carlgt1@qcn-web:/var/www/qcn/earthquakes/map_quakes.php qcn/earthquakes/
scp carlgt1@qcn-web:/var/www/qcn/earthquakes/recent_quakes.php qcn/earthquakes/
scp carlgt1@qcn-web:/var/www/qcn/earthquakes/popup.js qcn/earthquakes/
scp carlgt1@qcn-web:/var/www/qcn/earthquakes/view_events.php qcn/earthquakes/
scp carlgt1@qcn-web:/var/www/qcn/earthquakes/recent_quakes.php qcn/earthquakes/

#earthquakes/inc
scp carlgt1@qcn-web:/var/www/qcn/earthquakes/inc/index_earthquake.php qcn/earthquakes/inc
scp carlgt1@qcn-web:/var/www/qcn/earthquakes/inc/index_earthquake_sub.php qcn/earthquakes/inc
scp carlgt1@qcn-web:/var/www/qcn/earthquakes/inc/amp_v_dist.text qcn/earthquakes/inc
scp carlgt1@qcn-web:/var/www/qcn/earthquakes/inc/bash.env qcn/earthquakes/inc
scp carlgt1@qcn-web:/var/www/qcn/earthquakes/inc/csh.env qcn/earthquakes/inc
scp carlgt1@qcn-web:/var/www/qcn/earthquakes/inc/common.inc qcn/earthquakes/inc
scp carlgt1@qcn-web:/var/www/qcn/earthquakes/inc/CNelevatio2.txt qcn/earthquakes/inc
scp carlgt1@qcn-web:/var/www/qcn/earthquakes/inc/int_v1.cpt qcn/earthquakes/inc
scp carlgt1@qcn-web:/var/www/qcn/earthquakes/inc/dl.inc qcn/earthquakes/inc
scp carlgt1@qcn-web:/var/www/qcn/earthquakes/inc/earthquake_email.inc qcn/earthquakes/inc
scp carlgt1@qcn-web:/var/www/qcn/earthquakes/inc/earthquake_email.list qcn/earthquakes/inc
scp carlgt1@qcn-web:/var/www/qcn/earthquakes/inc/gmt_map.php qcn/earthquakes/inc
scp carlgt1@qcn-web:/var/www/qcn/earthquakes/inc/gmt_quakes.inc qcn/earthquakes/inc
scp carlgt1@qcn-web:/var/www/qcn/earthquakes/inc/gmt_scatter_script.csh qcn/earthquakes/inc
scp carlgt1@qcn-web:/var/www/qcn/earthquakes/inc/intensity.php qcn/earthquakes/inc
scp carlgt1@qcn-web:/var/www/qcn/earthquakes/inc/popup.inc qcn/earthquakes/inc
scp carlgt1@qcn-web:/var/www/qcn/earthquakes/inc/qcn_trigger_info.inc qcn/earthquakes/inc
scp carlgt1@qcn-web:/var/www/qcn/earthquakes/inc/revise_magnitude.csh qcn/earthquakes/inc
scp carlgt1@qcn-web:/var/www/qcn/earthquakes/inc/revise_magnitude.php qcn/earthquakes/inc
scp carlgt1@qcn-web:/var/www/qcn/earthquakes/inc/scatter_lines.xy qcn/earthquakes/inc
scp carlgt1@qcn-web:/var/www/qcn/earthquakes/inc/update_index_php.csh qcn/earthquakes/inc
scp carlgt1@qcn-web:/var/www/qcn/earthquakes/inc/worldcities_names.gmt qcn/earthquakes/inc
scp carlgt1@qcn-web:/var/www/qcn/earthquakes/inc/worldcitiespop.gmt qcn/earthquakes/inc
scp carlgt1@qcn-web:/var/www/qcn/earthquakes/inc/drag.js qcn/earthquakes/inc
scp carlgt1@qcn-web:/var/www/qcn/earthquakes/inc/CNtype2.txt qcn/earthquakes/inc
scp carlgt1@qcn-web:/var/www/qcn/earthquakes/inc/CNtype2_key.txt qcn/earthquakes/inc
scp carlgt1@qcn-web:/var/www/qcn/earthquakes/inc/amp_v_dist.text qcn/earthquakes/inc
scp carlgt1@qcn-web:/var/www/qcn/earthquakes/inc/amp_v_dist.theo qcn/earthquakes/inc

#earthquakes/view
scp carlgt1@qcn-web:/var/www/qcn/earthquakes/view/index.php qcn/earthquakes/view
scp carlgt1@qcn-web:/var/www/qcn/earthquakes/view/plot_data.sh qcn/earthquakes/view
scp carlgt1@qcn-web:/var/www/qcn/earthquakes/view/update_waveform.sh qcn/earthquakes/view
scp carlgt1@qcn-web:/var/www/qcn/earthquakes/view/view_data.php qcn/earthquakes/view
scp carlgt1@qcn-web:/var/www/qcn/earthquakes/view/plot_all_data.sh qcn/earthquakes/view

#rt_image
scp carlgt1@qcn-web:/var/www/qcn/rt_image/index.php qcn/rt_image/
scp carlgt1@qcn-web:/var/www/qcn/rt_image/ltn.php qcn/rt_image/
scp carlgt1@qcn-web:/var/www/qcn/rt_image/rt_triggers_DTN.xyz qcn/rt_image/
scp carlgt1@qcn-web:/var/www/qcn/rt_image/rt_triggers_LTN.xyz qcn/rt_image/
scp carlgt1@qcn-web:/var/www/qcn/rt_image/rt_triggers.xyz qcn/rt_image/
scp carlgt1@qcn-web:/var/www/qcn/rt_image/usb_sensors.php qcn/rt_image/

#rt_image/inc
scp carlgt1@qcn-web:/var/www/qcn/rt_image/inc/GMT_globe_grey.cpt qcn/rt_image/inc/
scp carlgt1@qcn-web:/var/www/qcn/rt_image/inc/GMT_gray.cpt qcn/rt_image/inc/
scp carlgt1@qcn-web:/var/www/qcn/rt_image/inc/gmt_quakes.inc qcn/rt_image/inc/
scp carlgt1@qcn-web:/var/www/qcn/rt_image/inc/int.cpt qcn/rt_image/inc/
scp carlgt1@qcn-web:/var/www/qcn/rt_image/inc/rt_images.sh qcn/rt_image/inc/
scp carlgt1@qcn-web:/var/www/qcn/rt_image/inc/update_data.inc qcn/rt_image/inc/

#qcn/inc
scp carlgt1@qcn-web:/var/www/qcn/inc/legal.inc qcn/inc/
scp carlgt1@qcn-web:/var/www/qcn/inc/google_translate.inc qcn/inc/
scp carlgt1@qcn-web:/var/www/qcn/inc/qcn_auto_detect.inc qcn/inc/
scp carlgt1@qcn-web:/var/www/qcn/inc/show_notices.inc qcn/inc/
scp carlgt1@qcn-web:/var/www/qcn/inc/contacts.inc qcn/inc/

## end
