pscp carlgt1@qcn-web:/var/www/boinc/qcnalpha/project_files.xml ../config/
pscp carlgt1@qcn-web:/var/www/boinc/qcnalpha/gui_urls.xml ../config/
pscp carlgt1@qcn-web:/var/www/boinc/qcnalpha/config.xml ../config/
pscp carlgt1@qcn-web:/var/www/boinc/qcnalpha/bin/generate_maptrig.sh ../config/
pscp carlgt1@qcn-web:/usr/local/apache2/conf/httpd.conf ../config/
pscp carlgt1@qcn-web:/usr/local/apache2/conf/drupal.conf ../config/
pscp carlgt1@qcn-web:/etc/init.d/httpd ../config/
pscp carlgt1@qcn-web:/var/www/boinc/qcnalpha/html/inc/cache.inc inc/
pscp carlgt1@qcn-web:/var/www/boinc/qcnalpha/html/inc/db_ops.inc inc/
pscp carlgt1@qcn-web:/var/www/boinc/qcnalpha/html/inc/forum.inc inc/
pscp carlgt1@qcn-web:/var/www/boinc/qcnalpha/html/inc/host.inc inc/
pscp carlgt1@qcn-web:/var/www/boinc/qcnalpha/html/inc/phoogle.inc inc/
pscp carlgt1@qcn-web:/var/www/boinc/qcnalpha/html/inc/prefs.inc inc/
pscp carlgt1@qcn-web:/var/www/boinc/qcnalpha/html/inc/user.inc inc/
pscp carlgt1@qcn-web:/var/www/boinc/qcnalpha/html/project/cache_parameters.inc project/
pscp carlgt1@qcn-web:/var/www/boinc/qcnalpha/html/project/project.inc project/
pscp carlgt1@qcn-web:/var/www/boinc/qcnalpha/html/project/project_news.inc project/
pscp carlgt1@qcn-web:/var/www/boinc/qcnalpha/html/project/project_specific_prefs.inc project/
pscp carlgt1@qcn-web:/var/www/boinc/qcnalpha/html/project/plate_boundary.inc project/
pscp carlgt1@qcn-web:/var/www/boinc/qcnalpha/html/user/account_finish.php user/
pscp carlgt1@qcn-web:/var/www/boinc/qcnalpha/html/user/account_finish_action.php user/
pscp carlgt1@qcn-web:/var/www/boinc/qcnalpha/html/user/create_account.php user/
pscp carlgt1@qcn-web:/var/www/boinc/qcnalpha/html/user/edit_host_info_form.php user/
pscp carlgt1@qcn-web:/var/www/boinc/qcnalpha/html/user/edit_host_info_action.php user/
pscp carlgt1@qcn-web:/var/www/boinc/qcnalpha/html/user/edit_user_info_form.php user/
pscp carlgt1@qcn-web:/var/www/boinc/qcnalpha/html/user/index.php user/
pscp carlgt1@qcn-web:/var/www/boinc/qcnalpha/html/user/forum_index.php user/
pscp carlgt1@qcn-web:/var/www/boinc/qcnalpha/html/user/maptrig.php user/
pscp carlgt1@qcn-web:/var/www/boinc/qcnalpha/html/user/maptrigtime.php user/
pscp carlgt1@qcn-web:/var/www/boinc/qcnalpha/html/user/results.php user/
pscp carlgt1@qcn-web:/var/www/boinc/qcnalpha/html/user/qcn.css user/
pscp carlgt1@qcn-web:/var/www/boinc/qcnalpha/html/user/show_host_detail.php user/
pscp carlgt1@qcn-web:/var/www/boinc/qcnalpha/html/user/server_status.php user/
pscp carlgt1@qcn-web:/var/www/boinc/qcnalpha/html/user/trigger.php user/
pscp carlgt1@qcn-web:/var/www/boinc/qcnalpha/html/ops/calendarDateInput.js ops/
pscp carlgt1@qcn-web:/var/www/boinc/qcnalpha/html/ops/calendar.jpg ops/
pscp carlgt1@qcn-web:/var/www/boinc/qcnalpha/html/ops/db_form.php ops/
pscp carlgt1@qcn-web:/var/www/boinc/qcnalpha/html/ops/db_action.php ops/
pscp carlgt1@qcn-web:/var/www/boinc/qcnalpha/html/ops/index.php ops/
pscp carlgt1@qcn-web:/var/www/boinc/qcnalpha/html/ops/next.gif ops/
pscp carlgt1@qcn-web:/var/www/boinc/qcnalpha/html/ops/prev.gif ops/
pscp carlgt1@qcn-web:/var/www/boinc/qcnalpha/html/ops/trig.php ops/
pscp carlgt1@qcn-web:/var/www/boinc/qcnalpha/html/ops/trigreq.php ops/
pscp carlgt1@qcn-web:/var/www/boinc/qcnalpha/html/ops/dbinfo.php ops/
pscp carlgt1@qcn-web:/var/www/boinc/qcnalpha/html/ops/generate_maptrig.php ops/
pscp carlgt1@qcn-web:/var/www/boinc/qcnalpha/html/ops/weeky-host.php ops/
