#!/bin/bash
#/bin/rm -f /tmp/qcn-backup.sql.gz
/bin/rm -f /tmp/qcn-backup.sql
/bin/nice -n19 /usr/local/mysql/bin/mysqldump -u root -pPWD --all-databases > /tmp/qcn-backup.sql
/bin/nice -n19 /usr/local/mysql/bin/mysqldump -u root -pPWD continual > /tmp/qcn-backup-continual.sql
#/bin/nice -n19 /bin/gzip /tmp/qcn-backup.sql
# note for the following line need to have .ssh id between root & carlgt1 setup
# also make sure that '.ssh/known_hosts' is setup to receive connections
/bin/nice -n19 /usr/bin/scp -C /tmp/qcn-backup.sql carlgt1@upl-private:
/bin/rm -f /tmp/qcn-backup.sql
