#############################################################################
# Makefile for building: QCNLive.app/Contents/MacOS/QCNLive
# Generated by qmake (2.01a) (Qt 4.7.0) on: Mon Nov 22 18:33:45 2010
# Project:  QCNLive.pro
# Template: app
# Command: /usr/bin/qmake -o QCNLive.xcodeproj/project.pbxproj QCNLive.pro
#############################################################################

QMAKE    = /Developer/QtSDK/Desktop/Qt/474/gcc/bin/qmake
QCNLive.xcodeproj/project.pbxproj: QCNLive.pro  /Developer/QtSDK/Desktop/Qt/474/gcc/mkspecs/macx-xcode/qmake.conf /Developer/QtSDK/Desktop/Qt/474/gcc/mkspecs/common/unix.conf \
		/Developer/QtSDK/Desktop/Qt/474/gcc/mkspecs/common/mac.conf \
		/Developer/QtSDK/Desktop/Qt/474/gcc/mkspecs/common/mac-g++.conf \
		/Developer/QtSDK/Desktop/Qt/474/gcc/mkspecs/qconfig.pri \
		/Developer/QtSDK/Desktop/Qt/474/gcc/mkspecs/modules/qt_webkit_version.pri \
		/Developer/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/qt_functions.prf \
		/Developer/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/qt_config.prf \
		/Developer/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/exclusive_builds.prf \
		/Developer/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/default_pre.prf \
		/Developer/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/default_pre.prf \
		/Developer/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/dwarf2.prf \
		/Developer/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/debug.prf \
		/Developer/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/default_post.prf \
		/Developer/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/default_post.prf \
		/Developer/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/x86.prf \
		/Developer/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/objective_c.prf \
		/Developer/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/ppc.prf \
		/Developer/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/warn_on.prf \
		/Developer/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/qt.prf \
		/Developer/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/unix/opengl.prf \
		/Developer/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/unix/thread.prf \
		/Developer/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/moc.prf \
		/Developer/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/rez.prf \
		/Developer/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/sdk.prf \
		/Developer/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/resources.prf \
		/Developer/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/uic.prf \
		/Developer/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/yacc.prf \
		/Developer/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/lex.prf \
		/Developer/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/include_source_dir.prf \
		/Developer/QtSDK/Desktop/Qt/474/gcc/lib/QtOpenGL.framework/QtOpenGL.prl \
		/Developer/QtSDK/Desktop/Qt/474/gcc/lib/QtGui.framework/QtGui.prl \
		/Developer/QtSDK/Desktop/Qt/474/gcc/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -o QCNLive.xcodeproj/project.pbxproj QCNLive.pro
/Developer/QtSDK/Desktop/Qt/474/gcc/mkspecs/common/unix.conf:
/Developer/QtSDK/Desktop/Qt/474/gcc/mkspecs/common/mac.conf:
/Developer/QtSDK/Desktop/Qt/474/gcc/mkspecs/common/mac-g++.conf:
/Developer/QtSDK/Desktop/Qt/474/gcc/mkspecs/qconfig.pri:
/Developer/QtSDK/Desktop/Qt/474/gcc/mkspecs/modules/qt_webkit_version.pri:
/Developer/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/qt_functions.prf:
/Developer/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/qt_config.prf:
/Developer/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/exclusive_builds.prf:
/Developer/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/default_pre.prf:
/Developer/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/default_pre.prf:
/Developer/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/dwarf2.prf:
/Developer/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/debug.prf:
/Developer/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/default_post.prf:
/Developer/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/default_post.prf:
/Developer/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/x86.prf:
/Developer/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/objective_c.prf:
/Developer/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/ppc.prf:
/Developer/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/warn_on.prf:
/Developer/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/qt.prf:
/Developer/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/unix/opengl.prf:
/Developer/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/unix/thread.prf:
/Developer/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/moc.prf:
/Developer/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/rez.prf:
/Developer/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/sdk.prf:
/Developer/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/resources.prf:
/Developer/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/uic.prf:
/Developer/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/yacc.prf:
/Developer/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/lex.prf:
/Developer/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/include_source_dir.prf:
/Developer/QtSDK/Desktop/Qt/474/gcc/lib/QtOpenGL.framework/QtOpenGL.prl:
/Developer/QtSDK/Desktop/Qt/474/gcc/lib/QtGui.framework/QtGui.prl:
/Developer/QtSDK/Desktop/Qt/474/gcc/lib/QtCore.framework/QtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o QCNLive.xcodeproj/project.pbxproj QCNLive.pro

