<?php

require_once("../inc/util.inc");
require_once("../inc/user.inc");
require_once("../inc/boinc_db.inc");
require_once("../inc/prefs.inc");
require_once("../inc/utils.inc");
require_once("../project/common.inc");

$user = get_logged_in_user();

page_top();
require_once(BASEPATH . "/qcn/earthquakes/inc/gmt_quakes.inc");


chdir(BASEPATH . '/boinc/sensor/html/user/');               // Several features wont work if we dont

$user = get_logged_in_user(true, true);
$psprefs = project_specific_prefs_parse($user->project_prefs);


echo "<p><h1>Rapid Earthquake Detection Service (REDS):</h1></p>\n";
echo "<p><img src=\"" . BASEURL . "/earthquakes/images/events.jpg\" width=\"350\" align=\"left\">\n";
echo "<p align=\"justify\">The Quake-Catcher Network rapidly locates earthquakes using data recorded on volunteer computers. You can receive instant notifications as QCN detects new earthquakes.  We are still working on our rapid earthquake magnitude estimation algorithms.  If you wish to receive emails when we detect an earthquake, please signup below.</p>\n";

echo "<p><strong>LEFT:</strong> A map of recently detected earthquakes.</p>\n";

echo "<p><table width=\"650\" border=\"1\"><tr><td bgcolor=\"#dddddd\">\n";  // Outer box around table 

echo "<p><table width=\"625\" border=\"0\" \n";
echo "<form name=\"_list\">\n";
echo "<tr><td></td><td><h2>";

//show_login($user);
echo "</h2></td></tr>\n";
echo "<tr><td width=\"200\" align=\"right\">Name:</td><td><input name=\"name\" type=\"text\" value=\"$user->name\"></td>\n"; 
echo "<tr><td width=\"200\" align=\"right\">Email:</td><td> <input name=\"name\" type=\"text\" value=\"$user->email_addr\"></td>\n";
echo "<tr><td widht=\"200\" align=\"right\">Global Min Magnitude:</td><td> <select name=\"mag_global\" id=\"mag_global\" >\n";
echo "                            <option value=\"3\">3</option>\n";
echo "                            <option value=\"4\">4</option>\n";
echo "                            <option value=\"5\">5</option>\n";
echo "                            <option value=\"6\" SELECTED>6</option>\n";
echo "                         </select> (Receive email if the estimated magnitude is greater than this value. Note, this is not intended to warning system.) </td></tr>\n";
echo "<tr><td width=\"200\" align=\"right\">Local Min Magnitude: </td><td><select name=\"mag_local\" id=\"mag_global\" > \n";
echo "                            <option value=\"3\">3</option>\n";
echo "                            <option SELECTED value=\"4\">4</option>\n";
echo "                            <option value=\"5\">5</option>\n";
echo "                            <option value=\"6\">6</option>\n";
echo "                         </select></td></tr>\n";

echo "<tr><td></td><td>\n";
terms_and_conditions();
echo "<p><input name=\"t_and_c\" type=\"checkbox\" value=\"t_and_c_checked\">Check if you have read Terms and Conditions (above).\n";
echo "<p><input id=\"submit\" class=\"button\" value=\"Add Me to the List\" type=\"button\">\n";

echo "</td></tr>\n";

echo "</table></td></tr></table>\n"; // End of tables
echo "Page created on \n". date('M d Y'). " at "; echo date('h:i:s'); echo " (UTC)\n";



page_end();

function terms_and_conditions() {

$text = "Quake-Catcher Network Online Standard Terms and Conditions:\n

PLEASE READ VERY CAREFULLY THESE TERMS AND CONDITIONS BEFORE REGISTERING TO RECEIVE INFORMATION FROM THE QUAKE-CATCHER NETWORK.  PARTICIPATION IN THE QUAKE-CATCHER NETWORK INDICATES THAT YOU ACCEPT THESE TERMS AND CONDITIONS.  IF YOU DO NOT ACCEPT THESE TERMS AND CONDITIONS, PLEASE DO NOT REGISTER FOR OR PARTICIPATE IN THE QUAKE-CATCHER NETWORK ONLINE PROGRAM.\n

Introduction. This agreement (\"Agreement\") between You and the Quake-Catcher Network (\"QCN\") and the QCN's affiliations (\"Stanford University\" and \"UC Riverside\" and others) consists of these QCN Rapid Event Detection Service (the \"Program\") Standard Terms and Conditions (\"Terms and Conditions\"). A description of the Program, as generally offered by QCN, is available at the Program Frequently Asked Questions (\"FAQ\") URL, located at https://qcn.stanford.edu/REDS/faq, or such other URL as QCN may provide from time to time. \"You\" or \"Publisher\" means any entity identified in an enrollment form submitted by the same or affiliated persons, and/or any agency or network acting on its (or their) behalf, which shall also be bound by the terms of this Agreement.

1.Program Participation. Participation in the Program is subject to QCN's prior approval and Your continued compliance with the Program Policies (\"Program Policies\"), located at https://qcn.stanford.edu/REDS/policies, and/or such other URL as QCN may provide from time to time. QCN reserves the right to refuse participation to any applicant or participant at any time in its sole discretion. By enrolling in the Program, You represent that You are at least 18 years of age and agree that QCN may serve (a) third party and/or QCN provided content (\"Content\"), provided, however, that if QCN serves non-compensated content, You will have the ability to opt out of receiving such Content as part of the Program, (b) related QCN queries and/or data links (collectively, \"Links\"), (c) QCN Web and/or Site search results (collectively, \"Search Results\"), and/or (d) QCN referral Links (\"Referral Buttons\"), each in connection with the Web site(s), media player(s), video content and/or mobile content that You designate, or such other properties expressly authorized in writing by QCN (including by electronic mail) (such other properties, \"Other Properties\"), and the Atom, RSS, or other feeds distributed through such Web site(s), media player(s), video content, mobile content and/or Other Properties (each such Web site, media player, video content, mobile content, Other Property or feed, a \"Property\"). For the avoidance of doubt, any reference in this Agreement or the Program Policies to an individual \"Web page\", \"Web site\", \"Web site page\" or the like that is part of the Property will also mean feeds and media players distributed through such Web site. Multiple accounts held by the same individual or entity are subject to immediate termination unless expressly authorized in writing by QCN (including by electronic mail).  In some circumstances expressly authorized in writing by QCN (including by electronic mail), You may enroll in the Program and create an account for the sole purpose of receiving information from QCN, and not, for purposes of clarification, for the purpose of displaying Ads, Links, Search Results and/or Referral Buttons on a Property.  If, however, You subsequently use your Account to participate in the Program (i.e. for the purpose of displaying Ads, Links, Search Results and/or Referral Buttons on a Property), then such use of the Program will be governed by the terms of this Agreement.\n

2.Implementation and Operation of Content, Search Results, and Referrals. You agree to comply with the specifications provided by QCN from time to time to enable proper delivery, display, tracking, and reporting of Content, Links, Search Results, Referral Buttons, and QCN Brand Features (as defined in Section 12 below) in connection with Your Property(ies), including without limitation by not modifying the Content or other programming provided to You by QCN in any way, unless expressly authorized in writing by QCN (including by electronic mail).\n

o REDS for Search. All search queries (including queries entered into an search box) must originate from individual human end users inputting data directly into a Search Box on Your Property(ies). You will send any and all queries (without editing, filtering, truncating, appending terms to or otherwise modifying such queries individually or in the aggregate) to QCN and QCN will use commercially reasonable efforts to provide You with corresponding Search Results and/or Content, as applicable and as available. Search Results and any accompanying Content will be displayed on Web pages (or Electronic mail) that may be hosted by QCN (each, a \"Search Results Page\"), and the format, look and feel of those Web pages hosted by QCN may be modified by QCN from time to time.\n

o REDS for Content. All content and Property-based Content (and Content served in response to end user clicks on and queries entered into Links, if any) shall be grouped by QCN and displayed with Links (where applicable) to end users of the Property(ies) as ad units (such groups of Content and/or Links collectively referred to as \"Content Units\") in standard formats as offered generally by QCN from time to time, as may be described in the FAQ. You may select a format approved by QCN for the display of Content Units in connection with the Property(ies), but You acknowledge and agree that Content and/or Links: (i) shall only be displayed in connection with the Property(ies), each of which is subject to review and approval by QCN in its discretion at any time; and (ii) shall be subject to the placement guidelines set forth herein.\n

o General; Serviced Pages; (i) It is Your responsibility to enable such features in accordance with the specifications provided by QCN, and (ii) QCN does not and cannot commit that all results (including Content, Links and Search Results) will be limited to results elected by enabling the recomended features. Some Program features are identified as \"Beta\" or otherwise unsupported (\"Beta Features\").  To the fullest extent permitted by law, Beta Features are provided \"as is\" and at Your option and risk.  You shall not disclose to any third party any information from Beta Features, existence of non-public Beta Features or access to Beta Features.\n

3.Parties' Responsibilities. You are solely responsible for the Property(ies), including all content and materials, maintenance and operation thereof, the proper implementation of QCN's specifications, and adherence to the terms of this Agreement, including compliance with the Program Policies. QCN reserves the right to investigate, at its own discretion, any activity that may violate this Agreement, including but not limited to any use of a software application to access Ads, Links, Search Results, or Referral Buttons or to complete any Referral Event, or any engagement in any activity prohibited by this Agreement. QCN is not responsible for anything related to Your Property(ies), including without limitation the receipt of queries from end users of Your Property(ies) or the transmission of data between Your Property(ies) and QCN. In addition, QCN shall not be obligated to provide notice to You in the event that any Content, Link, Search Result, or Referral Button is not being displayed properly to end users of the Property(ies).\n

4.Prohibited Uses. You shall not, and shall not authorize or encourage any third party to: (i) directly or indirectly generate spurious Content (including without limitation intentionally disturbing the QCN sensor) through any automated, deceptive, fraudulent or other invalid means, including but not limited to through repeated physical or electronic disturbance of the sensor, the use of robots or other automated content tools and/or computer generated content, and/or the unauthorized use of other electronic services and/or software; (ii) edit, modify, filter, truncate or change the order of the information contained in any Content, Link, Content Unit, Search Result, or Referral Button, or remove, obscure or minimize any Content, Link, Ad Unit, Search Result, or Referral Button in any way without authorization from QCN; (iii) display any Ad(s), Link(s), or Referral Button(s) on any Web page or any Web site that contains any pornographic, hate-related, violent, or illegal content; (vi) directly or indirectly access, launch, and/or activate Ads, Links, Search Results, or Referral Buttons through or from, or otherwise incorporate the Ads, Links, Search Results, or Referral Buttons in, any software application, Web site, or other means other than Your Property(ies), and then only to the extent expressly permitted by this Agreement; (iv) act in any way that violates any Program Policies posted on the QCN Web Site, as may be revised from time to time, or any other agreement between You and QCN (including without limitation the QCN AdWords program terms); (v) disseminate malware; (vi) create a new account to use the Program after QCN has terminated this Agreement with You as a result of your breach of this Agreement; or (vii) engage in any action or practice that reflects poorly on QCN or otherwise disparages or devalues QCN's reputation or goodwill. You acknowledge that any attempted participation or violation of any of the foregoing is a material breach of this Agreement and that we may pursue any and all applicable legal and equitable remedies against You, including an immediate suspension of Your account or termination of this Agreement, and the pursuit of all available civil or criminal remedies.\n

5.Termination; Cancellation. Subject to any third party agreements You may have with other QCN affiliations or Property(ies), You may stop displaying Content, Links, Searches, or Referral Buttons on any Property in the Program with or without cause at any time by removing the QCN Software or similar programming from Your Properties and or unsubscribing. You may terminate this Agreement with or without cause at any time by entering your Account details in the Subscription Termination Form (" . BASEURL . "/sensor/REDS_unsubscribe.php) or Account Termination Form (" . BASEURL . "/sensor/account_terminate.php) to cancel Your participation in the Program. This Agreement will be deemed terminated within ten (10) business days of QCN's receipt of Your notice. QCN may investigate any activity that may violate this Agreement. QCN may at any time, in its sole discretion, terminate all or part of the Program, terminate this Agreement, or suspend or terminate the participation of any Property in all or part of the Program for any reason. In addition, QCN reserves the right to terminate without notice any account that has not generated a sufficient number of valid clicks or generation of Content or Referral Buttons or valid impressions of Content (in each case as measured by QCN) for a period of two (2) months or more. Upon termination of participation of any Property in the Program or termination of this Agreement for any reason, Sections 5 through 9, and 12 through 15 shall survive termination.\n

6.Confidentiality. You agree not to disclose QCN Confidential Information without QCN's prior written consent. \"QCN Confidential Information\" includes without limitation: (a) all QCN software, technology, programming, specifications, materials, guidelines and documentation relating to the Program; and (b) any other information designated in writing by QCN as \"
Confidential\" or an equivalent designation. QCN Confidential Information does not include information that has become publicly known through no breach by You or QCN, or information that has been (i) independently developed without access to QCN Confidential Information, as evidenced in writing; (ii) rightfully received by You from a third party; or (iii) required to be disclosed by law or by a governmental authority.\n

7.No Guarantee. QCN makes no guarantee regarding the level of impressions of Content or clicks on any Referral Button, the timing of delivery of such impressions and/or clicks, the completion of Referral Events.  In addition, for the avoidance of doubt, QCN does not guarantee the Program will be operable at all times or during any down time (i) caused by outages to any public Internet backbones, networks or servers, (ii) caused by any failures of Your equipment, systems or local access services, (iii) for previously scheduled maintenance or (iv) relating to events beyond QCN's (or its affiliations's) control such as strikes, riots, insurrection, fires, floods, explosions, war, governmental action, labor conditions, earthquakes, natural disasters, or interruptions in Internet services to an area where QCN (or affiliations) or Your servers are located or co-located.\n

8.No Warranty. QCN MAKES NO WARRANTY, EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION WITH RESPECT TO CONTENT, LINKS, SEARCH, REFERRALS, AND OTHER SERVICES, AND EXPRESSLY DISCLAIMS THE WARRANTIES OR CONDITIONS OF NONINFRINGEMENT, MERCHANTABILITY, AND FITNESS FOR ANY PARTICULAR PURPOSE. TO THE EXTENT CONTENT, LINKS, AND SEARCH RESULTS ARE BASED ON OR DISPLAYED IN CONNECTION WITH NON-QCN CONTENT, QCN SHALL NOT HAVE ANY LIABILITY IN CONNECTION WITH THE DISPLAY OF SUCH ADS, LINKS, AND SEARCH RESULTS.\n

9.Limitations of Liability; Force Majeure. EXCEPT FOR ANY INDEMNIFICATION AND CONFIDENTIALITY OBLIGATIONS HEREUNDER OR YOUR BREACH OF ANY INTELLECTUAL PROPERTY RIGHTS AND/OR PROPRIETARY INTERESTS RELATING TO THE PROGRAM, (i) IN NO EVENT SHALL EITHER PARTY BE LIABLE UNDER THIS AGREEMENT FOR ANY CONSEQUENTIAL, SPECIAL, INDIRECT, EXEMPLARY, OR PUNITIVE DAMAGES WHETHER IN CONTRACT, TORT OR ANY OTHER LEGAL THEORY, EVEN IF SUCH PARTY HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES AND NOTWITHSTANDING ANY FAILURE OF ESSENTIAL PURPOSE OF ANY LIMITED REMEDY AND (ii) QCN HAS NO AGGREGATE LIABILITY TO PUBLISHER OR END USER UNDER THIS AGREEMENT FOR ANY CLAIM. Each party acknowledges that the other party has entered into this Agreement relying on the limitations of liability stated herein and that those limitations are an essential basis of the bargain between the parties. Without limiting the foregoing and except for payment obligations, neither party shall have any liability for any failure or delay resulting from any condition beyond the reasonable control of such party, including but not limited to governmental action or acts of terrorism, earthquake or other acts of God, labor conditions, and power failures.\n

10.Publicity. You agree that QCN may use any and all data and metadata Content related your account in presentations, marketing materials, participant lists, financial reports, Web site listings of data, Search Results Pages, and Referral Pages. If You wish to use QCN's trade names, trademarks, service marks, logos, domain names, and other distinctive brand features (\"Brand Features\"), You may do so, so long as such use is in compliance with this Agreement and in compliance with QCN's then current Brand Feature use guidelines, and any content contained or referenced therein, which guidelines may be found at the following URL: " . BASEURL . "/permissions/guidelines.html (or such other URL QCN may provide from time to time).\n

11.Representations and Warranties. You represent and warrant that (a) all of the information provided by You to QCN to enroll in the Program is correct and current; (b) You are the owner of each Property or You are legally authorized to act on behalf of the owner of such Property(ies) for the purposes of this Agreement and the Program; (c) You have all necessary right, power, and authority to enter into this Agreement and to perform the acts required of You hereunder; and (d) You have complied and will continue to comply with all applicable laws, statutes, ordinances, and regulations (including without limitation the CAN-SPAM Act of 2003 and any relevant data protection or privacy laws) in Your performance of any acts hereunder. You further represent and warrant that each Property and any material displayed therein: (i) comply with all applicable laws, statutes, ordinances, and regulations; (ii) do not breach and have not breached any duty toward or rights of any person or entity including, without limitation, rights of intellectual property, publicity or privacy, or rights or duties under consumer protection, product liability, tort, or contract theories; and (iii) are not pornographic, hate-related or otherwise violent in content.\n

12.Your Obligation to Indemnify. You agree to indemnify, defend and hold QCN, its agents, affiliates, subsidiaries, directors, officers, employees, and applicable third parties (e.g. relevant advertisers, syndication partners, licensors, licensees, consultants and contractors) (collectively \"Indemnified Person(s)\") harmless from and against any and all third party claims, liability, loss, and expense (including damage awards, settlement amounts, and reasonable legal fees), brought against any Indemnified Person(s), arising out of, related to or which may arise from Your use of the Program, the Property(ies), and/or Your breach of any term of this Agreement.\n

13.QCN Rights. You acknowledge that QCN owns all right, title and interest, including without limitation all Intellectual Property Rights (as defined below), in and to the Program (including QCN's ad serving technology, search technology, referral technology, and Brand Features, including implied licenses, and excluding items licensed by QCN from third parties and excluding any third party media player that may comprise the Property), and that You will not acquire any right, title, or interest in or to the Program except as expressly set forth in this Agreement. You will not modify, adapt, translate, prepare derivative works from, decompile, reverse engineer, disassemble or otherwise attempt to derive source code from any QCN services, software, or documentation, or create or attempt to create a substitute or similar service or product through use of or access to the Program or proprietary information related thereto. You will not remove, obscure, or alter QCN's copyright notice, Brand Features, or other proprietary rights notices affixed to or contained within any QCN services, software, or documentation (including without limitation the display of QCN's Brand Features with Content, Links, Search Boxes, Search Results, and/or Referral Buttons, as applicable). \"Intellectual Property Rights\" means any and all rights existing from time to time under patent law, copyright law, semiconductor chip protection law, moral rights law, trade secret law, trademark law, unfair competition law, publicity rights law, privacy rights law, and any and all other proprietary rights, as well as, any and all applications, renewals, extensions, restorations and re-instatements thereof, now or hereafter in force and effect worldwide.\n

14.Information Rights. QCN may retain and use, subject to the terms of the QCN Privacy Policy (located at " . BASEURL . "/privacy.php, or such other URL as QCN may provide from time to time), all information You provide, including but not limited to Property demographics and contact and billing information. You agree that QCN may transfer and disclose to third parties personally identifiable information about You for the purpose of approving and enabling Your participation in the Program, including to third parties that reside in jurisdictions with less restrictive data laws than Your own. QCN may also provide information in response to valid legal process, such as subpoenas, search warrants and court orders, or to establish or exercise its legal rights or defend against legal claims. QCN disclaims all responsibility, and will not be liable to You, however, for any disclosure of that information by any such third party. QCN may share non-personally-identifiable information about You, including Property URLs, Property-specific statistics and similar information collected by QCN, with advertisers, business partners, sponsors, and other third parties. In addition, You grant QCN the right to access, index and cache the Property(ies), or any portion thereof, including by automated means including Web spiders or crawlers.\n

15.Miscellaneous. This Agreement shall be governed by the laws of California, except for its conflicts of laws principles. Any dispute or claim arising out of or in connection with this Agreement shall be adjudicated in Santa Clara County, California. The parties specifically exclude from application to the Agreement the United Nations Convention on Contracts for the International Sale of Goods and the Uniform Computer Information Transactions Act. This Agreement constitutes the entire agreement between the parties with respect to the subject matter hereof. Any modifications to this Agreement must be made in a writing executed by both parties, by Your online acceptance of updated terms, or after Your continued participation in the Program after such terms have been updated by QCN. The failure to require performance of any provision shall not affect a party's right to require performance at any time thereafter, nor shall a waiver of any breach or default of this Agreement constitute a waiver of any subsequent breach or default or a waiver of the provision itself. If any provision herein is held unenforceable, then such provision will be modified to reflect the parties' intention, and the remaining provisions of this Agreement will remain in full force and effect. You may not resell, assign, or transfer any of Your rights hereunder. Any such attempt may result in termination of this Agreement, without liability to QCN. Notwithstanding the foregoing, QCN may assign this Agreement to any affiliate at any time without notice. The relationship between QCN and You is not one of a legal partnership relationship, but is one of independent contractors.\n";

echo "<textarea cols=\"50\" rows=\"20\">$text></textarea>\n";
}

?>
